### ISSUE TITLE
Make the plugin work with whalebrew redis

### ISSUE THREAD

**Issue by otherguy** [xxyzz/WordDumb#1]
I love your plugin and it's super useful!

One thing that would be great is if it would work with the [whalebrew](https://github.com/whalebrew/whalebrew) version of redis, instead of having to use the homebrew install.

**Comment by xxyzz** [comment]
On macOS, `redis-server` needs to be installed to `/usr/local/bin/` and that's where whalebrew installs packages. On other  systems, it needs to be in your `PATH`. It's doesn't matter which package manager you use.

But, dude... Why you need Docker to run a command?

**Comment by otherguy** [comment]
> On macOS, `redis-server` needs to be installed to `/usr/local/bin/` and that's where whalebrew installs packages. On other systems, it needs to be in your `PATH`. It doesn't matter which package manager you use.

That is correct, but the binary that `whalebrew` installs is called `redis`, not `redis-server`. Maybe you could check for both binaries and use the one that is available?

> But, dude... Why you need Docker to run a command that only depends on openssl?

Well, my work is with Docker and I use `whalebrew` (or custom aliases) for everything that I don't expect to run on at least a daily basis. It's very useful as images are deleted after they haven't been used for some time and automatically pulled again when they are needed. 

I could ask the same question about your choice of `redis`, when `sqlite` could be easily bundled with the plugin ;) 

> I guess whalebrew images can only uses files in `/workdir`.

True, but `/workdir` is the current working directory (`docker run -it -v "$(pwd)":/workdir -w /workdir $IMAGE "$@"`) so you can just return a relative path instead of an absolute path from `unzip_db` and it should work.

**Comment by xxyzz** [comment]
I believe most package managers won't tamper with the binary name,  whalebrew clearly isn't one of them.

Python sqlite3 is slow and noisy, I heard redis is fast so I give it a try. You can compare the performance yourself or simply checkout the github action test.

It might be impossible to get a relative path.

This feature has quite a few special cases to handle but most users won't need it. Please just install redis the normal way... Actually if you install it via homebrew, uninstall it then reinstall, the binary file is cached in your mac so it's faster than pull a image.

**Comment by otherguy** [comment]
Fair enough! I have patched the plugin locally to work with the whalebrew redis. 

Thank you for your help!
