### ISSUE TITLE
Generating X-Ray failed

### ISSUE THREAD

**Issue by uaoin** [xxyzz/WordDumb#100]
### Checkboxes

- [x] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

Generating word-wise it works but generating X-ray not work, it gives an error.

### System Information

OS: Windows 10
Calibre:6.11.0
WordDumb:3.28.2
Python:3.11.1

### Error message

```
calibre, version 6.11.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Harry Potter and the Deathly Hallows 
Job: "Generating Word Wise and X-Ray for Harry Potter and the Deathly Hallows" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
  File "calibre_plugins.worddumb.deps", line 175, in upgrade_pip
AttributeError: 'NoneType' object has no attribute 'splitlines'
 
Called with args: ((7, 'AZW3', 'S:\\books\\J.K. Rowling\\Harry Potter and the Deathly Hallows (7)\\Harry Potter and the Deathly Ha - J.K. Rowling.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001F0CFB40D30>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x000001F0CFB40B80>, 'abort': <threading.Event object at 0x000001F0CFB40FD0>, 'log': <calibre.utils.logging.GUILog object at 0x000001F0CFB43F40>} 

```

### Reproduce steps

1.Create X-Ray 
2.Get the error

**Comment by xxyzz** [comment]
Please post the output of this command `py -m pip show pip`. And did you follow the Python installation guide in [README](https://github.com/xxyzz/WordDumb#how-to-use)?

**Comment by uaoin** [comment]
> Please post the output of this command `py -m pip show pip`.

```
Name: pip
Version: 22.3.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: C:\Users\uaoin\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires:
Required-by:
```


>And did you follow the Python installation guide in [README](https://github.com/xxyzz/WordDumb#how-to-use)?

Yes, I downloaded Python from the website according to the readme file and installed it

**Comment by xxyzz** [comment]
Sorry, I have no clue why [`subprocess.CompletedProcess.stdout`](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess) is `None` on your machine.

Have you tried restarting your pc?

**Comment by uaoin** [comment]
I tried restarting my pc but it still gives the same error.

**Comment by xxyzz** [comment]
This error probably would be fixed on the master branch, please download the test plugin from GitHub Actions: https://github.com/xxyzz/WordDumb/actions/runs/4050955255
