### ISSUE TITLE
'CustomLemmasDialog' object has no attribute 'lang'

### ISSUE THREAD

**Issue by Vuizur** [xxyzz/WordDumb#105]
### Checkboxes

- [X] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

This bug occurs with the newest version of the add-on that I installed from the Github action artifacts.

Keep up the good work!

### System Information

OS: Windows 10
Python: 3.10

### Error message

```text
calibre, version 6.12.0
FEHLER: Unbehandelter Ausnahmefehler: <b>AttributeError</b>:'CustomLemmasDialog' object has no attribute 'lang'

calibre 6.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: WordDumb (3, 29, 0)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.custom_lemmas", line 302, in change_difficulty_limit
AttributeError: 'CustomLemmasDialog' object has no attribute 'lang'
```

### Reproduce steps

It is caused by clicking on Customize Wiktionary -> Setting a difficulty limit (in my case 3) -> and then clicking on save.

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/244d53ce9e4b3d8098ea09da2e23181f7c626b73 fixes this error. I should later check whether pylint could find these errors.

BTW, I made some changes recently to add support of Wiktionary definition for Kindle books by creating new Word Wise klld file. And I'm experimenting with the [dbnary](https://kaiko.getalp.org/about-dbnary/download/) data in order to support more Word Wise gloss languages, I though maybe you'd be interested in this.

**Comment by Vuizur** [comment]
Awesome, it works now. 👍

I think dbnary is a great idea, I always kind of ignored it because it only has very rudimental inflection support (I think they reimplemented some Wiktionary templates IIRC), but combined with spaCy lemmatization or maybe inflections taken from Wiktextract data it should work well.

Something that I think is really promising is the usage of translation tables (taken from kaikki + dbnary probably) to create dictionaries for any language pair (similar to https://github.com/karlb/wikdict-gen, but also for more exotic languages). I know nothing about RDF so far though (or the details of dbnary) 🙃.

**Comment by xxyzz** [comment]
Hi @Vuizur , I have extracted the Dbnary files in the [Proficiency repo](https://github.com/xxyzz/Proficiency). I also add support of new Word Wise gloss languages in WordDumb. Only German, French, Swedish and Croatian have inflection data, for other languages the "use pos" feature should be enabled.
