### ISSUE TITLE
Subprocess fails if python on windows is not using py launcher

### ISSUE THREAD

**Issue by Argyrum** [xxyzz/WordDumb#11]
**Describe the bug**
I recently installed the plugin but couldn't get it to work, it failed in the pip_install stage. I looked around following the traceback and the culprit is the py variable used to launch pip, which on a windows machine is assumed "py" for the py launcher command. In my case, i have bare python (the command is "python"), without the launcher, causing it to fail.

**System Information**
 - OS: Windows 10, 64bit
 - calibre version: 5.26.0, 64bit
 - Python version: 3.9.7, 64bit
 - Plugin version 3.13.1

**Error message**
Starting job: Generating X-Ray for Threadbare 
Job: "Generating X-Ray for Threadbare" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 83, in start_work
  File "calibre_plugins.worddumb.parse_job", line 24, in do_job
  File "calibre_plugins.worddumb.unzip", line 63, in install_libs
  File "calibre_plugins.worddumb.unzip", line 86, in pip_install
  File "subprocess.py", line 489, in run
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**To Reproduce**
Try to use the generate Xray function on a windows machine without pylauncher

**Proposed solution**
Would it be posible to check for "py" and in the case it fails use "python" as fallback?

**Screenshots or videos**
![imatge](https://user-images.githubusercontent.com/91261877/134503606-48790afe-bf2a-4f31-814a-dfaa9d8f2f8a.png)

**Comment by xxyzz** [comment]
Ah, if you leave the default installer settings along you won't get this error. Python Launcher uses the latest version of Python and it's included in your PATH, you should install it. Otherwise I have to check if it's Python 3 or Python 2 since both are named `python` and tell users to select the `add to PATH` option in the document that nobody reads.
