### ISSUE TITLE
Failed to generate X-ray with https://harrypotter.fandom.com (SQLite Database Locked ?)

### ISSUE THREAD

**Issue by ciaochiaociao** [xxyzz/WordDumb#119]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

Can't generate X-ray with Fandom for the Harry Potter Novel azw3 format. 

### System Information

OS: Ventura 13.3.1
Calibre: 6.16.0

### Error message

```text
calibre, version 6.16.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Harry Potter and the Sorcerer's Stone 
Job: "Generating Word Wise and X-Ray for Harry Potter and the Sorcerer's Stone" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 188, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "BBW9Q5C5CP", "book_path": "/Users/cwhsu/Calibre Library/J. K. Rowling/Harry Potter and the Sorcerer\'s Stone (4)/Harry Potter and the Sorcerer\'s Stone - J. K. Rowling.azw3", "acr": "Harry_Potter_and_the_Sorcerer\'s", "revision": "c2db9d96", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "utf-8", "useragent": "WordDumb/3.29.1 (https://github.com/xxyzz/WordDumb)", "book_fmt": "AZW3", "plugin_path": "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip"}', '{"use_pos": true, "search_people": true, "model_size": "md", "zh_wiki_variant": "tw", "fandom": "https://harrypotter.fandom.com", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu118", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((4, 'AZW3', "/Users/cwhsu/Calibre Library/J. K. Rowling/Harry Potter and the Sorcerer's Stone (4)/Harry Potter and the Sorcerer's Stone - J. K. Rowling.azw3", <calibre.ebooks.metadata.book.base.Metadata object at 0x11c70fa30>, 'en'), True, True) {'notifications': <queue.Queue object at 0x11c70ff70>, 'abort': <threading.Event object at 0x11c70feb0>, 'log': <calibre.utils.logging.GUILog object at 0x11c710040>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 40, in <module>
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/parse_job.py", line 355, in create_files
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/x_ray.py", line 197, in finish
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/mediawiki.py", line 488, in query_mediawiki
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/mediawiki.py", line 339, in query
  File "/Users/cwhsu/Library/Preferences/calibre/plugins/WordDumb.zip/mediawiki.py", line 261, in add_cache
sqlite3.OperationalError: database is locked
```

### Reproduce steps

1. Use WordDump function with the configuration steps shown in the following screenshot to generate X-ray for azw3 file
2. It does not finish well, but an error occurred

### Screenshots or videos

<img width="398" alt="image" src="https://user-images.githubusercontent.com/13917478/234450200-2d40440e-19d7-4b3d-a205-ba7b6fc6d0d7.png">

**Comment by xxyzz** [comment]
Could you upload the `~/Library/Preferences/calibre/plugins/worddumb-fandom/harrypotter.fandom.com.db` file?

You may need to compress that file to a zip file in order to upload to GitHub.

**Comment by ciaochiaociao** [comment]
> Could you upload the `~/Library/Preferences/calibre/plugins/worddumb-fandom/harrypotter.fandom.com.db` file?
> 
> You may need to compress that file to a zip file in order to upload to GitHub.

Sure.

[harrypotter.fandom.com.db.zip](https://github.com/xxyzz/WordDumb/files/11338897/harrypotter.fandom.com.db.zip)

**Comment by xxyzz** [comment]
I found this answer https://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked on stackoverflow, and you can try some steps from this answer:

1. Check no process is using the file by running this command: `fuser Library/Preferences/calibre/plugins/worddumb-fandom/harrypotter.fandom.com.db`
2. Upload this file if it exists: `Library/Preferences/calibre/plugins/worddumb-fandom/harrypotter.fandom.com.db-journal`
3. Delete `Library/Preferences/calibre/plugins/worddumb-fandom/harrypotter.fandom.com.db`, it's empty. Then rerun the plugin.

**Comment by ciaochiaociao** [comment]
@xxyzz Thank you so much! I appreciate your help. After simply removing all the db files in the folder, the issue has been solved. It turned out that the problem lies in the process terminated before not finishing up properly, which is indicated by the existence of the `*-journal` file as explained in the StackOverflow page you gave me. 

And before closing this issue, maybe it can be suggested that the handling of this database locking issue be coded into your program. For example, a piece of code of "removing the database files" may be used should an exception of the "database locking" event be emitted. Just a piece of my thought for your information

Anyway, thank you for your help.

**Comment by xxyzz** [comment]
I'd rather retain the db file for investigating similar database errors in the future. It would be harder to find what happened if the file was deleted.
