### ISSUE TITLE
tonnerre de brest

### ISSUE THREAD

**Issue by MichaelScofieldLogan** [xxyzz/WordDumb#132]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

calibre, version 6.21.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive 
Job: "Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
  File "calibre_plugins.worddumb.deps", line 81, in which_python
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((6, 'EPUB', 'C:\\Users\\DELL\\Calibre Library\\Dettmer, Philipp\\Immune _ A Journey into the Mysterio (6)\\Immune _ A Journey into the Mys - Dettmer, Philipp.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001D5F8F26AD0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001D5F8F27010>, 'abort': <threading.Event object at 0x000001D5F8F26FE0>, 'log': <calibre.utils.logging.GUILog object at 0x000001D5F8F26D70>} 
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### System Information

calibre, version 6.21.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive 
Job: "Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
  File "calibre_plugins.worddumb.deps", line 81, in which_python
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((6, 'EPUB', 'C:\\Users\\DELL\\Calibre Library\\Dettmer, Philipp\\Immune _ A Journey into the Mysterio (6)\\Immune _ A Journey into the Mys - Dettmer, Philipp.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001D5F8F26AD0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001D5F8F27010>, 'abort': <threading.Event object at 0x000001D5F8F26FE0>, 'log': <calibre.utils.logging.GUILog object at 0x000001D5F8F26D70>} 
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### Error message

```text
calibre, version 6.21.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive 
Job: "Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
  File "calibre_plugins.worddumb.deps", line 81, in which_python
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((6, 'EPUB', 'C:\\Users\\DELL\\Calibre Library\\Dettmer, Philipp\\Immune _ A Journey into the Mysterio (6)\\Immune _ A Journey into the Mys - Dettmer, Philipp.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001D5F8F26AD0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001D5F8F27010>, 'abort': <threading.Event object at 0x000001D5F8F26FE0>, 'log': <calibre.utils.logging.GUILog object at 0x000001D5F8F26D70>} 
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

### Reproduce steps

calibre, version 6.21.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive 
Job: "Generating Word Wise and X-Ray for Immune : A Journey into the Mysterious System That Keeps You Alive (9780593241332): A Journey into the Mysterious System That Keeps You Alive" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
  File "calibre_plugins.worddumb.deps", line 81, in which_python
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((6, 'EPUB', 'C:\\Users\\DELL\\Calibre Library\\Dettmer, Philipp\\Immune _ A Journey into the Mysterio (6)\\Immune _ A Journey into the Mys - Dettmer, Philipp.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001D5F8F26AD0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001D5F8F27010>, 'abort': <threading.Event object at 0x000001D5F8F26FE0>, 'log': <calibre.utils.logging.GUILog object at 0x000001D5F8F26D70>} 
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### Screenshots or videos

![image](https://github.com/xxyzz/WordDumb/assets/47894543/14dc34aa-f157-49cf-a67c-2ce1e043695d)

**Comment by xxyzz** [comment]
You need to install Python: https://xxyzz.github.io/WordDumb/installation.html#install-python-3-10-and-pip.

**Comment by xxyzz** [comment]
[v3.29.3](https://github.com/xxyzz/WordDumb/releases/tag/v3.29.3) will pop up a window to tell Windows users to install Python if it's not installed. Thanks for reporting this error and I'll close the issue now.
