### ISSUE TITLE
Worddumb can't find Python

### ISSUE THREAD

**Issue by CAndrewA** [xxyzz/WordDumb#133]
Worddumb can't find python. I have python installed. 

OS: macOS Monterey 12.3
Python Version: 3.11.4
Plugin Version: 3.29.3
Calibre Version: 6.21 

calibre, version 6.21.0 (darwin, embedded-python: True)
We want... a shrubbery!: Can't find Python. Please read the document of how to install Python.

Starting job: Generating Word Wise and X-Ray for Foundation 
Job: "Generating Word Wise and X-Ray for Foundation" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
    install_deps("lxml", notifications)
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
    PY_PATH, py_version = which_python()
  File "calibre_plugins.worddumb.deps", line 84, in which_python
    raise Exception("PythonNotFound")
Exception: PythonNotFound
 
Called with args: ((31, 'KFX', '/Users/xyz/Documents/Stuff/Calibre/Isaac Asimov/Foundation (31)/Foundation - Isaac Asimov.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x14b57dff0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x14b57c0d0>, 'abort': <threading.Event object at 0x14b57fe80>, 'log': <calibre.utils.logging.GUILog object at 0x14b57fd30>}

**Comment by xxyzz** [comment]
Please read the document: https://xxyzz.github.io/WordDumb/installation.html

macOS users should install Python from Homebrew and don't use Rosetta if your mac has arm chip.
