### ISSUE TITLE
Python Not Found

### ISSUE THREAD

**Issue by guptaanurag2106** [xxyzz/WordDumb#139]
### Checkboxes

- [x] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

I am facing issues setting the environment variable for python in the plugin. I have Python 3.9.12 installed via Miniconda3 in “D:/software/miniconda3/python.exe”. I have tried setting PYTHON_PATH to point to the EXE file, but it doesn't seem to resolve the issue.

### System Information

OS: Windows 11 22H2 22621.1992
Calibre Version: 6.23.0
Plugin Version: 3.29.5
Python Version: 3.9.12 (Using via miniconda3)

### Error message

```text
calibre, version 6.23.0 (win32, embedded-python: True)
We want... a shrubbery!: Can't find Python. Please read the document of how to install Python.

Starting job: Generating Word Wise and X-Ray for The Power of Your Subconscious Mind 
Job: "Generating Word Wise and X-Ray for The Power of Your Subconscious Mind" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 37, in install_deps
  File "calibre_plugins.worddumb.deps", line 88, in which_python
Exception: PythonNotFound
 
Called with args: ((29, 'KFX', 'D:\\books\\calibre\\Joseph Murphy\\The Power of Your Subconscious Mind (29)\\The Power of Your Subconscious - Joseph Murphy.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000207D3504FD0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x00000207D3505030>, 'abort': <threading.Event object at 0x00000207D3505000>, 'log': <calibre.utils.logging.GUILog object at 0x00000207D3505210>}
```

### Reproduce steps

-

**Comment by xxyzz** [comment]
Please read https://xxyzz.github.io/WordDumb/installation.html, that page has instruction of installing Python and Python 3.9 is not supported.

If you have to use miniconda, make sure the binary file path is in the `PATH` variable, the installers usually take care of that. `PATH` is used for Linux and mac, not sure about Windows.
