### ISSUE TITLE
utf-8 error

### ISSUE THREAD

**Issue by barukh27** [xxyzz/WordDumb#15]
Hi there!

I'm getting this issue:

calibre, version 5.33.2
ERROR: Excepción no considerada: <b>UnicodeDecodeError</b>:'utf-8' codec can't decode byte 0xf3 in position 13: invalid continuation byte

calibre 5.33.2 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 45, 0) && Count Pages (1, 11, 1) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0) && Kindle Collections (1, 7, 29) && Reading List (1, 7, 6) && WordDumb (3, 14, 3)
Traceback (most recent call last):
  File "calibre\gui2\__init__.py", line 502, in dispatch
  File "calibre_plugins.worddumb.main", line 52, in done
  File "calibre_plugins.worddumb.main", line 82, in job_failed
  File "calibre_plugins.worddumb.main", line 105, in subprocess_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 13: invalid continuation byte

Hope you can help me.

Thanks.

**Comment by xxyzz** [comment]
Please install the [latest build](https://github.com/xxyzz/WordDumb/suites/4573863574/artifacts/123098806). It should fix this error but you'll get a new error which reveals the real culprit.
