### ISSUE TITLE
No Xray appears for ebook on android

### ISSUE THREAD

**Issue by wafflelily** [xxyzz/WordDumb#164]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

When trying to add xray to an ebook and load it into my android phone to read via the kindle app, I can read the book, but there's no xray options for that book. I can see xray for other books that I have bought via amazon.
Running worddumb seemed to generate everything as it should, on my computer i can see the epub and kfx versions of the files next to the xray file which has lots of data inside.
But when worddumb puts the files into my phone, it seems to only put the kfx or android files in.
Manually dragging files into the phone also doesn't work.

### Operating System name and version

Windows 10

### Python version

3.10.9

### calibre version

6.29.0

### WordDumb plugin version

3.29,7

### Error message

```text
no error message
```

### Plugin settings and reproduce steps

![image](https://github.com/xxyzz/WordDumb/assets/37215827/fefabed3-ec2f-47b1-8fe8-36a865dabdc1)
![image](https://github.com/xxyzz/WordDumb/assets/37215827/ce28343f-978d-4b53-a709-c174f97f17c7)
I click create X ray

### Generated files, screenshots or videos

![image](https://github.com/xxyzz/WordDumb/assets/37215827/97dcfdf3-74af-4b63-b7cd-7da27b1fdc8f)
![image](https://github.com/xxyzz/WordDumb/assets/37215827/cee38958-6ff9-49bc-9147-424edd59e3ec)

**Comment by xxyzz** [comment]
Does the `BBFO...` folder on your phone contains XRAY file?

**Comment by wafflelily** [comment]
![image](https://github.com/xxyzz/WordDumb/assets/37215827/8331fe94-3a94-4930-be66-0fc7d651c320)
It didn't, so I manually added it there to see if that would work, made no difference

**Comment by xxyzz** [comment]
The XRay file need to be renamed to "XRAY.ASIN.acr.db". I sorry to day I don't know why the xray file wasn't sent to Android phone.

**Comment by wafflelily** [comment]
I renamed it to that and it didn't work. I also copied that file and put it in other folder locations too and it still didn't work.

**Comment by xxyzz** [comment]
You have to change the "asin" and "acr" in the filename. You can get these values by running this command:

```
$ calibre-debug -r "KFX Input" -- -j  kfx_file_path
```

the `asset_id` in the output is the `acr` value.
