### ISSUE TITLE
kindle can't react on azw3 format book and kll files created by using worddumb plugins

### ISSUE THREAD

**Issue by lovits** [xxyzz/WordDumb#166]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

today I use  worddumb,the X-RAY and WORD WISE function don't work well,converted epub books can use x-ray and word wise,but azw3 books and related kll files and asc files can't work.my kindle version is 5.16.4

### Operating System name and version

WIN10

### Python version

3.12

### calibre version

6.29

### WordDumb plugin version

3.29.7

### Error message

```text
.
```

### Plugin settings and reproduce steps

.

**Comment by xxyzz** [comment]
Please provide more information, what's the book language and your plugin configurations? And what do you mean converted EPUB book works?  Does the created files have the same ASIN of the book file, and are they sent to your Kindle device?

**Comment by lovits** [comment]
I use this plugin to translate english phases into chinese,I found the epub book can be created and send to kindle normally,but azw3 book and related kll files and asn files can't work out. here is my configruations[Uploading 8TKEP]0KNMB$76VEDG4AC6V.png…]()

**Comment by lovits** [comment]
![8TKEP 0KNMB$76VEDG4AC6V](https://github.com/xxyzz/WordDumb/assets/124361371/97871181-76e8-42ed-8ac9-6d3213ccde5a)
![HY(FT`H7S6 X630(RDC3 GR](https://github.com/xxyzz/WordDumb/assets/124361371/e1c5c362-a244-4ee0-bd6b-a64cacd42787)
![K_YKR)NN~DR7X)1_YOMIK0P](https://github.com/xxyzz/WordDumb/assets/124361371/79b53a54-6885-4235-966b-689313cc5d43)

**Comment by lovits** [comment]
word wise and wiki dic : english to chinese,spaCy model :big.other is  default configruation

**Comment by lovits** [comment]
![image](https://github.com/xxyzz/WordDumb/assets/124361371/86db56a0-0c17-4beb-9548-eed3bb729524)
this is my azw3 book and converted epub book,I can use sending EPUB to Kindle to read ,but import azw3 book and kll files asc files to kindle can't help.

**Comment by xxyzz** [comment]
Please delete the book from you device then let the plugin to copy the AZW3 book and created files to Kindle.

**Comment by lovits** [comment]
the plugin can't copy azw3 book and created files to kindle automatically,instead when I run the plugin to create epub book,it will send epub book to kindle.it's so weird.

**Comment by lovits** [comment]
![image](https://github.com/xxyzz/WordDumb/assets/124361371/29abd2a1-ae88-458d-9b4a-c7cab2b936c7)
this is created epub book and send to kindle automatically 
![image](https://github.com/xxyzz/WordDumb/assets/124361371/53b1836f-5185-40df-9c91-dc4dba5264fb)
this is azw3 book and created files in local dictionary

**Comment by xxyzz** [comment]
Oh you're using Scrible, the plugin can't copy files to Scrible if you have updated the firmware which uses MTP.

**Comment by lovits** [comment]
oh,I try to copy word wise and xray files to kindle scribe manually however it doesn't work.If you can update this plugin to support MTP,I will appreciate it very much,for the reason I have some problems reading English book

**Comment by lovits** [comment]
In addition,I can sucessfully use this plugin in my kpw5 device which version is 5.16.4 and USB mode,when I copy azw3 book and the files created by plugin to my kindle scribe,what surprises me is that the word wise and xray can sucessfully work on the same book.

**Comment by xxyzz** [comment]
I have pushed some commits to the master branch to add support of MTP devices, please download the test plugin from GitHub Actions artifacts.

**Comment by xxyzz** [comment]
Other user has confirmed https://github.com/xxyzz/WordDumb/commit/d0cf598ca092727efbc1d8312f0f7d586bedf337  could send files to Scribe, I'll close this issue now.

**Comment by lovits** [comment]
OK，thanks
