### ISSUE TITLE
Python version 3.11 error after update

### ISSUE THREAD

**Issue by Daniyal-Javani** [xxyzz/WordDumb#178]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

It's not possible to install python version 3.11 on Ubuntu 22.04 LTS: https://askubuntu.com/questions/1374341/apt-get-upgrade-does-not-work-after-updating-python

Is there any way to force the plugin to use `/usr/bin/python3.12` instead of `/usr/bin/python3` ?

Or is there any other solution?

I'm getting this error: Outdated Python version https://justpaste.it/2gn7x

### Operating System name and version

Ubuntu 22.04

### Python version

3.10

### calibre version

7.3.0

### WordDumb plugin version

3.30.0

### Error message

```text
Outdated Python
```

### Plugin settings and reproduce steps

It happens just by installing the latest version of calibre and worddumb

**Comment by xxyzz** [comment]
You could set the Python interpreter path in the plugin settings window.

**Comment by Daniyal-Javani** [comment]
Oh sorry! Thanks, it works with this setting.
