### ISSUE TITLE
Error: Please use KindleUnpack's '-s' option to split the book.

### ISSUE THREAD

**Issue by iamfree139** [xxyzz/WordDumb#191]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

when simply using WordDumb on a book, it is giving this error "Please use KindleUnpack's '-s' option to split the book."

### Operating System name and version

MacOS Sonoma

### Python version

3.11.7

### calibre version

7.5.1

### WordDumb plugin version

3.31.0

### Error message

```text
calibre, version 7.4.0 (darwin, embedded-python: True)
Joint MOBI: Please use KindleUnpack's '-s' option to split the book.

Starting job: Generating Word Wise and X-Ray for Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential 
Job: "Generating Word Wise and X-Ray for Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
    get_asin_etc(data, set_en_lang=set_en_lang)
  File "calibre_plugins.worddumb.metadata", line 166, in get_asin_etc
    data.mobi_html = extract_mobi(data.book_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.worddumb.metadata", line 186, in extract_mobi
    raise Exception("JointMOBI")
Exception: JointMOBI
 
Called with args: (ParseJobData(book_id=13, book_path='/Users/ajay/Calibre Library/Tiago Forte/Building a Second Brain_ A Proven Method to Organize Your Digital Life and Unlock Your Creative (13)/Building a Second Brain_ A Proven Method t - Tiago Forte.mobi', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x1244a5f10>, book_fmt='MOBI', book_lang='en', useragent='', plugin_path='', spacy_model='', create_ww=True, create_x=True, asin='B09MDNDYYF', acr='epubor.com', revision='00000000', kfx_json=None, mobi_html=b'', mobi_codec='utf-8'),) {'notifications': <queue.Queue object at 0x1213ccb90>, 'abort': <threading.Event at 0x1243fb7d0: unset>, 'log': <calibre.utils.logging.GUILog object at 0x130242a10>}
```

### Plugin settings and reproduce steps

<img width="496" alt="Screenshot 2024-02-22 at 3 09 42 PM" src="https://github.com/xxyzz/WordDumb/assets/135931740/2378f293-cf32-40ff-995c-9d58ecb4b915">

**Comment by iamfree139** [comment]
it was working yesterday

**Comment by xxyzz** [comment]
That's a joint mobi book and can't be processed, you need to use [KindleUnpack](https://github.com/kevinhendricks/KindleUnpack) or other tools to split the book.

**Comment by iamfree139** [comment]
@xxyzz hey man, anyway to add wordwise and xray to document that are sent by email. its a book i send by email so i can sync it with other devices. When sending the book through calibre it is working. but i also want it to sync with other devices
