### ISSUE TITLE
Anyway to add wordwise and xray to document that are sent by email.

### ISSUE THREAD

**Issue by iamfree139** [xxyzz/WordDumb#195]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

Its a book i send by email so i can sync it with other devices. When sending the book through Calibre it is working, but i also want it to sync with other devices. 

### Operating System name and version

MacOS Sonoma

### Python version

3.11.7

### calibre version

7.5.1

### WordDumb plugin version

3.31.0

### Error message

```text
Help plz
```

### Plugin settings and reproduce steps

<img width="496" alt="Screenshot 2024-02-27 at 2 03 19 PM" src="https://github.com/xxyzz/WordDumb/assets/135931740/cd64f187-52cf-490c-ac81-4e481e5830e2">

**Comment by xxyzz** [comment]
I don't know how Kindle sync works, you probably need to set a valid ASIN data to the book file. And the files created from this plugin can't be synced.

**Comment by iamfree139** [comment]
@xxyzz 
- no i just need the wordwise in kindle not on other devices, while maintain the document in amazon cloud.
- Maybe first generating file normally then copy those files to kindle download folder, something like that.

**Comment by xxyzz** [comment]
The file sent through email is a personal document not a book, only a book can have word wise.

I know nothing about kindle cloud sync, sorry I can't help you.
