### ISSUE TITLE
wordwise returns the wrong word

### ISSUE THREAD

**Issue by bxshi** [xxyzz/WordDumb#196]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

I was able to use worddumb to generate wordwise and load it on Kindle, but the annotated word and definition does not match the actual word.

Some examples: 

- Actual word: phenomenon
- Wordwise: shows the explanation of mayoress

I did not see any error message during the process so not sure what goes wrong. I also tried to uninstall and reinstall the plugin, the issue persists. 

I have attached a screenshot of the issue and the generated azw3 + sdr folder. Please feel free to share some pointers on what might be the causes and I'd love to help dig into this. Thank you.

### Operating System name and version

Mac Sonoma 14.2.1 (23C71)

### Python version

3.12

### calibre version

7.6.0

### WordDumb plugin version

3.31.1

### Error message

```text
No actual error message.
```

### Plugin settings and reproduce steps

Click worddumb, create wordwise.
After that, it will automatically copy the book to kindle.
Open the book on kindle, and I see the wordwise always return the explanation of a different word.

### Generated files, screenshots or videos

Example file and wordwise file (azw3 + sdr folder):
[azw3_and_sdr.zip](https://github.com/xxyzz/WordDumb/files/14471217/azw3_and_sdr.zip)

Screenshot on kindle showing the wrong wordwise: 
![IMG_3732](https://github.com/xxyzz/WordDumb/assets/1314883/327bdb01-04f7-4636-84d0-6f5ec440d98c)

**Comment by xxyzz** [comment]
If you enabled the "use Wiktionary" option, you need to change word wise language to Chinese on your Kindle.

**Comment by bxshi** [comment]
Thank you, that's precisely why, it works now!
