### ISSUE TITLE
Epub generation with disabled POS seems to be broken

### ISSUE THREAD

**Issue by Vuizur** [xxyzz/WordDumb#199]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

When unticking the "Use POS" option, the epub generation currently seems to not be working. It doesn't insert any ruby tags, and while it inserts hyperlinks for the words to be defined, they are apparently broken.

I tested the disabled "Use POS" option last time on 24.02., and back then it worked flawlessly.

### Operating System name and version

Windows 10

### Python version

3.12

### calibre version

7.5.1

### WordDumb plugin version

newest master commit

### Error message

```text
-
```

### Plugin settings and reproduce steps

Disabling "Use Pos", and then creating "Word Wise" for any book.

### Generated files, screenshots or videos

[Viechnyi muzh (260).zip](https://github.com/xxyzz/WordDumb/files/14558584/Viechnyi.muzh.260.zip)
(This is a public domain stressed Russian book, but I also got the same result with a normal French book.

**Comment by xxyzz** [comment]
Please check the latest master branch commit, this bug should be fixed now.

**Comment by Vuizur** [comment]
Awesome, it really is fixed. Thanks a lot!
