### ISSUE TITLE
Not able to created word-wise file for KFX book 

### ISSUE THREAD

**Issue by west-vleteren** [xxyzz/WordDumb#201]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

calibre, version 7.6.0 (darwin, embedded-python: True)
Welcome to dependency hell: Please delete '/Users/z.tian/Library/Preferences/calibre/plugins/worddumb-libs-py*' folder, and try again.

Starting job: 正在为《The Hobbit: The Classic Bestselling Fantasy Novel》生成生词提示 
Job: "正在为《The Hobbit: The Classic Bestselling Fantasy Novel》生成生词提示" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
    get_asin_etc(data, set_en_lang=set_en_lang)
  File "calibre_plugins.worddumb.metadata", line 123, in get_asin_etc
    from calibre_plugins.kfx_input.kfxlib import YJ_Book
ModuleNotFoundError: No module named 'calibre_plugins.kfx_input'
 
Called with args: (ParseJobData(book_id=513, book_path='/Users/z.tian/Calibre 书库/J. R. R. Tolkien/The Hobbit_ The Classic Bestselling Fantasy Novel (513)/The Hobbit_ The Classic Bestselling Fantas - J. R. R. Tolkien.kfx', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x1323d5c10>, book_fmt='KFX', book_lang='en', useragent='', plugin_path='', spacy_model='', create_ww=True, create_x=False, asin='', acr='', revision='', kfx_json=None, mobi_html=b'', mobi_codec=''),) {'notifications': <queue.Queue object at 0x132362d90>, 'abort': <threading.Event at 0x1323d7790: unset>, 'log': <calibre.utils.logging.GUILog object at 0x1323c5450>} 

### Plugin settings and reproduce steps

Hi there, the plugin was excellent for azw3, but recently, I wanna read a book which is transferred via "send to Kindle"; it is KFX format. I naively copied the kll file(from azw3) to the KFX book directory, but it didn't work, so I wanna use the plugin to generate a new file for KFX, and the bug came out. That's how it is.

**Comment by xxyzz** [comment]
Please read the document, you need to install the KFX Input plugin and let the plugin uploads the book files.
