### ISSUE TITLE
X-Ray files being placed in wrong folder

### ISSUE THREAD

**Issue by Thiago4532** [xxyzz/WordDumb#206]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I assume this is happening because the book name is too large, but I am not sure, the plugin is placing the files in the wrong folder.
![image](https://github.com/xxyzz/WordDumb/assets/19158283/6966e62d-cc2a-4ad6-9e2d-9bb5824770fe)

Instead of placing X-Ray files in the folder with a large name, it creates a second with the title cutted off. If I move the files from the cutted folder to the normal folder the X-Ray works normally.

The name of the folder that WordDumb uses is the same name Calibre uses internally to store the ebook file:
![image](https://github.com/xxyzz/WordDumb/assets/19158283/40ab5978-c163-4a2d-9c0e-e4b03bc4b817)

So maybe WordDumb is using this name instead of the complete book name? Not sure though.

### Plugin settings and reproduce steps

Use WordDumb in a book that has the name Avatar, the Last Airbender: The Rise of Kyoshi and the author is F. C. Yee.

**Comment by xxyzz** [comment]
I changed the code to use book path because calibre's function returns lower case path on MTP device , I have asked calibre developer for help...

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/bcab9a846f617d5010244c2dfd6dd45d1e41853b should fix this issue, you could download test plugin from here: https://github.com/xxyzz/WordDumb/actions/runs/8737818123
