### ISSUE TITLE
Keyerror:zh_cn

### ISSUE THREAD

**Issue by Dieofu** [xxyzz/WordDumb#207]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

calibre, version 7.8.0
错误： 未处理的异常: <b>KeyError</b>:'zh_cn'

calibre 7.8  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
EXE path: E:\Software\Calibre\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (2, 10, 0) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && WordDumb (3, 31, 2)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.ui", line 101, in run
  File "calibre_plugins.worddumb.ui", line 88, in get_metadata_of_selected_books
  File "calibre_plugins.worddumb.ui", line 89, in <listcomp>
  File "calibre_plugins.worddumb.metadata", line 62, in check_metadata
KeyError: 'zh_cn'

### Plugin settings and reproduce steps

using word dumb functions on any English books

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/9c3e3f75afe81adb851da6f898f437ab007283ac should fix the error.

**Comment by Dieofu** [comment]
Should I just update word dumb from calibre?
Or I should download files from GitHub?
Thanks

xxyzz ***@***.***>于2024年4月16日 周二08:45写道：

**Comment by xxyzz** [comment]
You could download the test versions from [GitHub Actions Artifacts](https://github.com/xxyzz/WordDumb/actions/runs/8705765899) then install the test plugin zip file in calibre.

**Comment by Dieofu** [comment]
Thank you very much, it fixes the  issue

xxyzz ***@***.***>于2024年4月16日 周二09:57写道：
