### ISSUE TITLE
The word wise cant get in my PDF

### ISSUE THREAD

**Issue by Sergiopalmero97** [xxyzz/WordDumb#208]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I change the type of document *From PDF to AZW3* and when i try to install the plugin WordDumb it occurs and error.

### Plugin settings and reproduce steps

WordDumb. I try to get the wordwise and error.

**Comment by xxyzz** [comment]
What's the error message?

**Comment by xxyzz** [comment]
PDF is not supported.
