### ISSUE TITLE
"Customize X-Ray" returns an error

### ISSUE THREAD

**Issue by evashi23** [xxyzz/WordDumb#209]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

"Create X-Ray" seems to work fine but "Customize X-Ray" does not. It returns the following error: 

calibre, version 7.9.0
ERROR: Unhandled exception: <b>TypeError</b>:cannot unpack non-iterable MetaDataResult object

calibre 7.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /private/var/folders/rp/05x456t91wd8jxjs58md9stc0000gn/T/AppTranslocation/B27E4F90-A7DC-455D-88ED-4675BD86729A/d/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 10, 0) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Modify ePub (1, 8, 3) && Quality Check (1, 13, 10) && WordDumb (3, 31, 2)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.ui", line 77, in open_custom_x_ray_dialog
    for _, _, book_paths, mi, _ in get_metadata_of_selected_books(self.gui, True):
        ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable MetaDataResult object

### Plugin settings and reproduce steps

0. Updated to the latest version of WordDumb. 
1.  Clicked "Create X-Ray" on a book
2. Clicked "Customize X-Ray" on the same book
3. Got the error message

**Comment by xxyzz** [comment]
Should be fixed in master branch, you can download test version from https://github.com/xxyzz/WordDumb/actions/runs/8782519738
