### ISSUE TITLE
xray issue

### ISSUE THREAD

**Issue by majant0** [xxyzz/WordDumb#21]
my log was too long for here. view log file here: https://pastebin.com/B0pPGrvb

Last portion:

----------------------------------------
  ERROR: Failed building wheel for numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.2.3; however, version 22.0.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by xxyzz** [comment]
Does https://github.com/xxyzz/WordDumb/commit/69768d0109a26e2fdb8d27a9d7e638721d0b325c fixes the error? You can install this zip file on calibre manually to test: [worddumb-69768d0109a26e2fdb8d27a9d7e638721d0b325c.zip](https://github.com/xxyzz/WordDumb/files/8149864/worddumb-69768d0109a26e2fdb8d27a9d7e638721d0b325c.zip)

**Comment by majant0** [comment]
Not sure what's that's telling me. I did run that pip install command the first time I got the error and it upgraded my pip to the latest. still got the error.

**Comment by xxyzz** [comment]
You need to install the plugin I uploaded in my last comment. Upgrade pip alone won't solve the problem.

**Comment by xxyzz** [comment]
There was an error in that commit, please try this file: [worddumb-79468635a351b761cca938c9f74c407703cdcff8.zip](https://github.com/xxyzz/WordDumb/files/8150188/worddumb-79468635a351b761cca938c9f74c407703cdcff8.zip)

**Comment by majant0** [comment]
that appears to have fixed the issue.
