### ISSUE TITLE
X-Ray deleteing text after an X-Ray instance in epub

### ISSUE THREAD

**Issue by KeePach** [xxyzz/WordDumb#212]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

When creating X-Ray for epubs, if the last paragraph of a chapter contains an X-Ray instance, the text after the last x-ray instance gets erased

### Plugin settings and reproduce steps

0. Connect the device to calibre
1. open the Worddumb pluging and click "Create X-Ray"
2. wait for the x-ray creation and  upload of the epub to device
3. open book on device

### Generated files, screenshots or videos
[books.zip](https://github.com/xxyzz/WordDumb/files/15136190/books.zip)

_No response_

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/0c267e601173b7e8bfb16737f91eeef2b1000741 should fix this bug, test version can be downloaded from https://github.com/xxyzz/WordDumb/actions/runs/8858373801

**Comment by KeePach** [comment]
fixed
