### ISSUE TITLE
error when try to use the plugin english to hebrew

### ISSUE THREAD

**Issue by maorisraelii** [xxyzz/WordDumb#216]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I recived an error whrn I try to use the plugin on english books with hebrew wordwise

calibre, version 7.10.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Saving customized lemmas 
Job: "Saving customized lemmas" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.config", line 359, in dump_lemmas_job
  File "calibre_plugins.worddumb.deps", line 31, in install_deps
  File "calibre_plugins.worddumb.deps", line 103, in which_python
  File "calibre_plugins.worddumb.utils", line 52, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: (True, WindowsPath('C:/Users/maor/AppData/Roaming/calibre/plugins/worddumb-lemmas/en/wiktionary_en_he_v0.db'), 'en') {'notifications': <queue.Queue object at 0x000001AFD5222690>, 'abort': <threading.Event at 0x1afd5221610: unset>, 'log': <calibre.utils.logging.GUILog object at 0x000001AFD5222ED0>} 

### Plugin settings and reproduce steps

1.choose english book
2. make sure the defenition leng is hebrew and book leng is english
3. use worddumn plugin
4.  u recived the error

**Comment by xxyzz** [comment]
I guess you didn't install Python? Please read https://xxyzz.github.io/WordDumb/installation.html#install-python-3-11-and-pip
