### ISSUE TITLE
How can I disable or toggle Wordwise in Koreader?

### ISSUE THREAD

**Issue by Thamone** [xxyzz/WordDumb#218]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I just tried this plugin today on both my Kindle and Koreader (on my Kobo) and it's working great. With Kindle I can toggle Wordwise, but in Koreader I cannot find an option to disable it. I've tried all the footnote settings but nothing change.
What should I do to disable it?

### Plugin settings and reproduce steps

“Style tweaks” -> “In-page footnotes”  uncheck every options, nothing change

### Generated files, screenshots or videos

![Reader_2024-05-15_105705](https://github.com/xxyzz/WordDumb/assets/28747875/959b1bd5-e322-44d3-a9f6-5c92fa3ed1b1)

**Comment by xxyzz** [comment]
You can't.

Maybe you can hide them with some CSS rules.

**Comment by Thamone** [comment]
> You can't.
> 
> Maybe you can hide them with some CSS rules.

Thank you very much. In that case, I will use it only for books read on Kindle.

**Comment by xxyzz** [comment]
You can only add X-Ray data without Word Wise data from the drop down button:

![Screenshot from 2024-05-16 10-58-33](https://github.com/xxyzz/WordDumb/assets/21101839/340cf59e-9b1d-487f-b7f4-943be74f85b1)
