### ISSUE TITLE
Can't x ray and wordwise

### ISSUE THREAD

**Issue by minsusan** [xxyzz/WordDumb#222]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

When I use the plugin, there isn't any error message showed up. But when I send the modified file to Kindle through the website, it says the document couldn't be delivered. Even when I try with the cable, it doesn't show up in my Kindle. The original .epub file still works, though.

### Plugin settings and reproduce steps

1. Click on WordDumb Button
2. See nothing
3. Error

**Comment by xxyzz** [comment]
This plugin only support books send to device through USB cable.
