### ISSUE TITLE
Incorrect annotations

### ISSUE THREAD

**Issue by torears** [xxyzz/WordDumb#223]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

Wordwise shows unrelated annotations. For instance, annotation for word "gritty" was shown as "a section of a stadium", "chin" was "lacking good qualities". I tested it with KTX, AZW3 and MOBI formats but didn't affect the result.

My environment is Calibre 7.11, Worddumb 3.31.4, python 3.11 and Kindle 5.16.8.

### Plugin settings and reproduce steps

<img width="1004" alt="lemma_gloss" src="https://github.com/xxyzz/WordDumb/assets/170846860/9e185bf6-e478-4a27-ae3d-2836df22e2ec">
<img width="505" alt="worddumb customization" src="https://github.com/xxyzz/WordDumb/assets/170846860/24bb0649-dc83-4a2f-9064-55d6977d109d">

### Generated files, screenshots or videos

![screenshot](https://github.com/xxyzz/WordDumb/assets/170846860/b2357fba-1642-4c20-9840-154e138e7d50)

**Comment by xxyzz** [comment]
You need to change Word Wise language to Chinese on Kindle if "Use Wiktionary" option is enabled.

**Comment by torears** [comment]
You're absolutely right! it fixed the issue right away. Thank you very much for prompt support.
