### ISSUE TITLE
Cannot X-ray or Wordwise - FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by djvr97** [xxyzz/WordDumb#224]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

Can not use Word wise or X-ray, keep getting error - FileNotFoundError: [WinError 2] The system cannot find the file specified

Redownloaded epub file, converted to KFX, no problem. When trying to use plugin, get the error. 

Full error message attached
[KFX Error.txt](https://github.com/user-attachments/files/15526574/KFX.Error.txt)

### Plugin settings and reproduce steps

1. Downloaded  epub
2. converted to kfx 
3. Plugged in kindle
4. Clicked pluging
5. Error popped up

**Comment by xxyzz** [comment]
Have you installed Python? Please read the [installation](https://xxyzz.github.io/WordDumb/installation.html) document.

The plugin should show a warning window when Python is not installed.

**Comment by djvr97** [comment]
Python is installed and on latest version

**Comment by xxyzz** [comment]
Have you installed the py launcher? It's installed by default: https://docs.python.org/3/using/windows.html

**Comment by xxyzz** [comment]
Close as resolved, this error should be fixed by setting the Python path manually if it can't be found automatically.
