### ISSUE TITLE
Keyerror:zh_cn happeded on newest version

### ISSUE THREAD

**Issue by ccboxes** [xxyzz/WordDumb#228]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

The log file is attached at the end.
[calibre, version 7.12.zip](https://github.com/user-attachments/files/15759933/calibre.version.7.12.zip)

### Plugin settings and reproduce steps

create X-ray for any book.

**Comment by littlezhanzhan** [comment]
我也遇到了类似的问题

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/ca6ce96cc2b10beaf08d291a010250a9007fa2e3 should fix this bug, please download the test version from GitHub Actions artifacts.

**Comment by littlezhanzhan** [comment]
> [ca6ce96](https://github.com/xxyzz/WordDumb/commit/ca6ce96cc2b10beaf08d291a010250a9007fa2e3) should fix this bug, please download the test version from GitHub Actions artifacts.

it have been fixed! thank you so much!
