### ISSUE TITLE
x-ray didn't show up on kindle

### ISSUE THREAD

**Issue by jackstewert** [xxyzz/WordDumb#23]
**Describe the bug**
when i transfer the file to kindle, the x-ray didn't show up

**System Information**
 - OS: Macos 12.2.1
 - calibre version: 5.37, 64bit
 - Python version: 2.7.18
 - Plugin version 3.18.4

**To Reproduce**
1. Go to 'WordDumb plugin'
2. Click on 'generate x-ray'
3. after the job is done send it to your kindle
4. x-ray doesn't appear

**Extra Information**
the kindle stays on airplane mode

**Comment by xxyzz** [comment]
Send book via calibre's `send to device` button doesn't send the X-Ray file. You have to let the plugin send it, connect your kindle to calibre then click the plugin menu.

**Comment by jackstewert** [comment]
I tried it but it didn't worked 
i pluged in my kindle select the files and then  click on the plugin, the job finished but didn't show on the kindle

**Comment by xxyzz** [comment]
Please upload your book. Let's see whether I can reproduce it.

**Comment by jackstewert** [comment]
this is the kfx file
https://drive.google.com/file/d/1qndRP94T9vWkpVw3htS8EQpeQDlKtT1L/view?usp=sharing

**Comment by xxyzz** [comment]
X-Ray works fine on my Kindle. Are you sure you did the same as the usage video in [README](https://github.com/xxyzz/WordDumb#how-to-use) and no error occurred?

**Comment by jackstewert** [comment]
I redid it all again and now it worked 
I dont why it didn't worked before maybe because I send the file first and then clicked on the plugin whereas now i just plugged in my kindle and then clicked on the plugin

**Comment by jackstewert** [comment]
Anyways thank you for you help and your time

**Comment by jackstewert** [comment]
also btw how did you change the theme of your calibre

**Comment by xxyzz** [comment]
You mean icon theme?
<img width="920" alt="Screen Shot 2022-03-06 at 16 41 20" src="https://user-images.githubusercontent.com/21101839/156915672-9c8fa8b3-d693-4365-9673-e5adca903a2a.png">

**Comment by jackstewert** [comment]
yes I'm really new to calibre thank you

**Comment by Daniyal-Javani** [comment]
> Send book via calibre's `send to device` button doesn't send the X-Ray file. You have to let the plugin send it, connect your kindle to calibre then click the plugin menu.

@xxyzz That would be great if there was a way to send the X-Ray file to device without recreating it. Sometimes it takes too long to create it for large books.

**Comment by xxyzz** [comment]
If a generated file is not sent to a device, it'll be used next time when a device is connected.
