### ISSUE TITLE
Added successfully, open and read failed.

### ISSUE THREAD

**Issue by SsumingLau** [xxyzz/WordDumb#236]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I added word wise to the ePub file, but did not add X-Ray. Then I transferred the generated file “bookname_word_wise.epub” to my Kindle device via https://www.amazon.com/-/zh/sendtokindle. However, when I download and open the book on Kindle, the device shows an error message: 'An error occurred. If you purchased this content from Amazon, please remove it from your device and re-download from [Cloud].'（translated from Chinese）. I am unable to read it.

Additionally, if adding word wise to a MOBI file, I need to manually copy the .kll file to the Kindle's book folder. The 'send to device' feature in Calibre does not automatically copy this file over. I wonder if this functionality can be fixed. Thank you."

### Plugin settings and reproduce steps

Enable POS type.
The others are all default.

**Comment by xxyzz** [comment]
Please connect your Kindle to calibre using a USB cable then click the plugin icon or drop down button to send the book and generated files. For more usage info, please read https://xxyzz.github.io/WordDumb/usage.html
