### ISSUE TITLE
Error creating Word Wise and X-Ray for books in Calibre

### ISSUE THREAD

**Issue by n9nexx** [xxyzz/WordDumb#241]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

calibre, version 7.13.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for The Gunslinger 
Job: "Generating Word Wise and X-Ray for The Gunslinger" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 211, in do_job
  File "calibre_plugins.worddumb.utils", line 53, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['C:\\Users\\JRMC_\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', 'C:\\Users\\JRMC_\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 60, "book_path": "C:\\\\Users\\\\JRMC_\\\\Calibre Library\\\\Stephen King\\\\The Gunslinger (60)\\\\The Gunslinger - Stephen King.azw3", "mi": null, "book_fmt": "AZW3", "book_lang": "en", "useragent": "WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\JRMC_\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_trf", "create_ww": true, "create_x": true, "asin": "BBRJEL3921", "acr": "The_Gunslinger", "revision": "2b238b33", "kfx_json": null, "mobi_html": null, "mobi_codec": "utf-8"}', '{"use_pos": true, "search_people": true, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": true, "preferred_formats": ["AZW3", "MOBI", "EPUB", "KFX", "AZW"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": true, "cuda": "cu121", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "C:\\\\Users\\\\JRMC_\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python312\\\\python.exe", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=60, book_path='C:\\Users\\JRMC_\\Calibre Library\\Stephen King\\The Gunslinger (60)\\The Gunslinger - Stephen King.azw3', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x000001F444E99890>, book_fmt='AZW3', book_lang='en', useragent='WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\JRMC_\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_trf', create_ww=True, create_x=True, asin='BBRJEL3921', acr='The_Gunslinger', revision='2b238b33', kfx_json=None, mobi_html=None, mobi_codec='utf-8'),) {'notifications': <queue.Queue object at 0x000001F43E8BCC10>, 'abort': <threading.Event at 0x1f43e89f250: unset>, 'log': <calibre.utils.logging.GUILog object at 0x000001F43E89DD10>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 37, in <module>
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 237, in create_files
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 763, in load_spacy
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\types.py", line 25, in <module>
    from .compat import cupy, has_cupy
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\compat.py", line 35, in <module>
    import torch
  File "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\JRMC_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\torch\lib\cufftw64_11.dll" or one of its dependencies.

### Plugin settings and reproduce steps

Kindle Format: AZW3, MOBI, EPUB, KFX, AZW (in that order)
Boxes Ticked: Use POS type... Fetch X-Ray people... Run spaCy with GPU... Add Locator map to...
Boxes not ticked: Remove word wise and xray links...

CUDA Version: 12.1
spaCy size: Large
X-ray occurences: 1

### Generated files, screenshots or videos

![image](https://github.com/xxyzz/WordDumb/assets/174970994/4fb54441-2885-4527-a29a-176e3bcc93bd)

**Comment by xxyzz** [comment]
Downgrade CUDA or disable "use GPU" option, please read the install doc more carefully.
