### ISSUE TITLE
Kindle doesn't support EPUB format natively, please convert the book format then try again.

### ISSUE THREAD

**Issue by gabrielfmagalhaes** [xxyzz/WordDumb#244]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

Sorry to bother, but from what I read, WordDumb supports epub, mobi, and other formats, but it only works when I add an epub book. Is that right, or is it just me?

```
calibre, version 7.12.0
Kindle doesn't support EPUB: Kindle doesn't support EPUB format natively, please convert the book format then try again.
```

### Plugin settings and reproduce steps

0. Download an epub book
1. Add to Calibre
2. Click on WordDumb icon
3. Receive an error

### Generated files, screenshots or videos

![image](https://github.com/xxyzz/WordDumb/assets/87721980/a6b6de52-e881-4dc4-ab0f-e969d452610f)

**Comment by gabrielfmagalhaes** [comment]
Honestly, even when using a MOBI file, it doesn't work (WordWise is not applying). This is what worked for me:
1. Download an epub book
2. Convert to AZW3 manually through calibre
3. Click on the WordDumb icon

**Comment by xxyzz** [comment]
I think the error message is pretty clear? Please convert book to a Kindle compatible format first, then run the plugin.

If azw3 works for you, mobi should also works.

**Comment by d-belteshazzar** [comment]
Kindle is no longer support other formats but epub, when I clicked epub, then worddumb is not allowing me to send file.
If I choose other formats, my kindle scribe cannot find out ebook.  Please help.

![Image](https://github.com/user-attachments/assets/e347f793-ab05-4947-87f4-28fb6613c48b)

![Image](https://github.com/user-attachments/assets/fb254afc-867d-4875-a3c5-22f553f74948)
