### ISSUE TITLE
Danish to English word wise not working

### ISSUE THREAD

**Issue by enhaohaotan** [xxyzz/WordDumb#245]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I think my config is correct, because it can succefully work on English to English word wise.

But when I use the same setting on Danish books (with Danish to English word wise), not a single Dansih word is explianed correctly. I think it misunderstood it as some other languages. I could see that the downloaded vocabulary is danish, and is explained correctly. But as soon as it is on a danish book, it's not. I got no error message.

And no matter how I set the languages, next time I open it, the book language will turn to Catalan. I'n not sure if this is a bug.

### Plugin settings and reproduce steps

Worddumb is the same plugin I use in Calibre
I just set the languages and clicked the star to generate and send book to kindle.

**Comment by xxyzz** [comment]
Change Word Wise language to Chinese on Kindle to display Wiktionary definitions.

And book language is not a savable option.

**Comment by xxyzz** [comment]
Resolved in mobileread forum posts.
