### ISSUE TITLE
eBook gets transferred without cover image

### ISSUE THREAD

**Issue by sepsol** [xxyzz/WordDumb#25]
**Describe the bug**
Everything worked flawlessly, my only complaint is that the cover of the ebook doesn't get transferred to the Kindle Basic (10th Gen).

**System Information**
 - OS: macOS Monterey
 - calibre version: 5.40
 - Python version: 2.17.18
 - Plugin version 3.19.0

**Error message**
N/A

**To Reproduce**
Send a book with WordDumb over to your Kindle device using a USB cable and notice that it doesn't have any cover.

**Expected behavior**
For it to have a cover. I was able to get it with cover even when I tried to manually send the `.mobi` file generated by Calibre.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by xxyzz** [comment]
Does connect your Kindle to calibre again restore the cover? More information: https://www.mobileread.com/forums/showthread.php?t=329945

**Comment by xxyzz** [comment]
Close due to a [similar issue](https://github.com/xxyzz/WordDumb/issues/82) was resolved.
