### ISSUE TITLE
Feature Request: Different MediaWiki URLs for different books

### ISSUE THREAD

**Issue by Laura7089** [xxyzz/WordDumb#251]
I think it would be a useful feature to allow the user to override the custom MediaWiki link on a book-by-book basis, so that books which have their own wikis can pull from those while others can still use Wikipedia etc.

At the moment, this is only possible by manually changing the global plugin settings before each run of WordDumb, I would like books to "remember" their own wikis.

If this sounds like a desirable feature (and it doesn't already exist/I've misunderstood), I'm happy to try my hand with a PR.

**Comment by xxyzz** [comment]
I think even if create x-ray file repeatedly(rare IMO) for the same book the current code could remember the Mediawiki API. I'm reluctant(or lazy) to implement this feature, sorry. Too much headache with pyqt UI code...
