### ISSUE TITLE
WordDump doesn't create language layer file how it used to do

### ISSUE THREAD

**Issue by Pawel193** [xxyzz/WordDumb#252]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I used it once some time ago and fell in love with it, but when today I tried to generate language layer file in order to enable wordWise for another ebook it didn't work. Instead of creating language layer file it created another EPUB file where in fact after some words were their explanations in brackets, but it's completely not the same and actually makes reading more harder instead of making it easier. It's due to some update or something? Please let me know if I can somehow make it work like it used to, because it was really super useful. 

### Plugin settings and reproduce steps

My plugin settings are default, I downloaded the latest update.

**Comment by xxyzz** [comment]
If you're using a Kindle and the book only has EPUB format, you must convert the book to a Kindle supported format first then use this plugin.

**Comment by Pawel193** [comment]
Dear me, I should've thought that I had to do something differently than the last time. I was sure that it worked fine for EPUBs, though I obviously had converted those files into AZW3 on the first use. Sorry for stupid question then and thanks for the fast response!

**Comment by xxyzz** [comment]
The plugin won't upload EPUB book to Kindle, it'll show a warning window says EPUB is not supported by Kindle. I guess you upload the generated EPUB file manually and calibre converts the book format.
