### ISSUE TITLE
Database Disk Image is Malformed for Books in Russian (Calibre plugin)

### ISSUE THREAD

**Issue by sdd264** [xxyzz/WordDumb#253]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

Every time I try to create X-ray for books in Russian language, this error happens. Works okay for English books though. Also, when Kindle is connected, it takes an eternity to download some Kindle en-ru file.

calibre, version 7.16.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise и X-Ray for Видоизмененный углерод. Такеси Ковач: Видоизмененный углерод. Сломленные ангелы. Пробужденные фурии 
Job: "Generating Word Wise и X-Ray for Видоизмененный углерод. Такеси Ковач: Видоизмененный углерод. Сломленные ангелы. Пробужденные фурии" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 210, in do_job
  File "calibre_plugins.worddumb.utils", line 50, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\saido\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 130, "book_path": "C:\\\\Users\\\\saido\\\\\\u0411\\u0438\\u0431\\u043b\\u0438\\u043e\\u0442\\u0435\\u043a\\u0430 calibre\\\\Richard K. Morghan\\\\Vidoizmieniennyi ughlierod. Takiesi (130)\\\\Vidoizmieniennyi ughlierod. Tak - Richard K. Morghan_en.mobi", "mi": null, "book_fmt": "MOBI", "book_lang": "ru", "useragent": "WordDumb/3.33.0 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\saido\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "ru_core_news_md", "create_ww": true, "create_x": true, "asin": "BBES6TM792", "acr": "Vidoizmieniennyi_ughlierod._Tak", "revision": "949d3096", "kfx_json": null, "mobi_html": null, "mobi_codec": "utf-8"}', '{"search_people": false, "model_size": "md", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": false, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5, "cuda": "cu121", "fandom": "", "use_gpu": false, "use_pos": true}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=130, book_path='C:\\Users\\saido\\Библиотека calibre\\Richard K. Morghan\\Vidoizmieniennyi ughlierod. Takiesi (130)\\Vidoizmieniennyi ughlierod. Tak - Richard K. Morghan_en.mobi', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x0000025AA2CCA310>, book_fmt='MOBI', book_lang='ru', useragent='WordDumb/3.33.0 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\saido\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='ru_core_news_md', create_ww=True, create_x=True, asin='BBES6TM792', acr='Vidoizmieniennyi_ughlierod._Tak', revision='949d3096', kfx_json=None, mobi_html=None, mobi_codec='utf-8'),) {'notifications': <queue.Queue object at 0x0000025AA2CB7750>, 'abort': <threading.Event at 0x25aa5416790: unset>, 'log': <calibre.utils.logging.GUILog object at 0x0000025AA5416D50>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saido\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 37, in <module>
  File "C:\Users\saido\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 251, in create_files
  File "C:\Users\saido\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 771, in create_spacy_matcher
  File "C:\Users\saido\AppData\Roaming\calibre\plugins\WordDumb.zip\dump_lemmas.py", line 102, in save_spacy_docs
sqlite3.DatabaseError: database disk image is malformed

### Plugin settings and reproduce steps

Creating X-ray file for a .MOBI format.

**Comment by xxyzz** [comment]
Maybe the downloaded file is corrupted, click the "Restore defaults" button at the bottom left of the customize lemmas windows to delete the database file.

en_ru database file is only 3MB, maybe a network problem? Check if you could download files from GitHub release: https://github.com/xxyzz/Proficiency/releases/tag/v0.5.20

**Comment by sdd264** [comment]
I couldn't find "Restore defaults" button, so I just replaced lemma files through file explorer. It seems working, thank you very much. By the way, may you show me where the beforementioned button is?

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/8ce3ac0bfe86a5b2dbf6c234de0e7cea4f76188b should fix this partial downloaded file error.

**Comment by tripple626** [comment]
Hi, thank you for your response. I am really new here and trying to follow the instructions you mentioned above. Since I am using macOS, it seems there might be some differences compared to Windows. I cannot find the 'Restore Default' button or the Lemmas window. Could you please provide step-by-step instructions on how to find them? additionally, I have been downloading the files you mentioned above but i don't know where should i put that file.

**Comment by tripple626** [comment]
> Hi, thank you for your response. I am really new here and trying to follow the instructions you mentioned above. I got error messages, could you please help me ?
> 
> calibre, version 7.26.0 (darwin, embedded-python: True) Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.
> 
> Starting job: Downloading Word Wise file Job: "Downloading Word Wise file" failed with error: Traceback (most recent call last): File "calibre/gui2/threaded_jobs.py", line 85, in start_work File "calibre_plugins.worddumb.deps", line 165, in download_word_wise_file tar_f.extractall(download_folder) File "tarfile.py", line 2264, in extractall File "tarfile.py", line 2327, in _extract_one File "tarfile.py", line 2410, in _extract_member File "tarfile.py", line 2463, in makefile File "tarfile.py", line 252, in copyfileobj File "bz2.py", line 164, in read File "_compression.py", line 68, in readinto File "_compression.py", line 99, in read EOFError: Compressed file ended before the end-of-stream marker was reached
> 
> Called with args: (True, 'en', {'add_locator_map': False, 'gloss_lang': 'en', 'mediawiki_api': '', 'minimal_x_ray_count': 1, 'model_size': 'md', 'python_path': '', 'remove_link_styles': False, 'search_people': True, 'use_wiktionary_for_kindle': True, 'zh_wiki_variant': 'cn', 'show_change_kindle_ww_lang_warning': False}) {'notifications': <queue.Queue object at 0x127beda10>, 'abort': <threading.Event at 0x127c0c850: unset>, 'log': <calibre.utils.logging.GUILog object at 0x127c0cc10>}

if i unchecked wiktionary = calibre, version 7.26.0
ERROR: Unhandled exception: <b>DatabaseError</b>:database disk image is malformed

calibre 7.26  embedded-python: True
macOS-15.3.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '24.3.0', 'Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:06 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('15.3.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: WordDumb (3, 33, 2)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.config", line 240, in open_choose_lemma_lang_dialog
    custom_lemmas_dlg = CustomLemmasDialog(
                        ^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.worddumb.custom_lemmas", line 70, in __init__
    self.init_sql_table(is_kindle)
  File "calibre_plugins.worddumb.custom_lemmas", line 87, in init_sql_table
    self.check_empty_kindle_gloss()
  File "calibre_plugins.worddumb.custom_lemmas", line 196, in check_empty_kindle_gloss
    for (gloss,) in custom_db_conn.execute("SELECT short_def FROM senses LIMIT 1"):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.DatabaseError: database disk image is malformed

**Comment by xxyzz** [comment]
Have you click the "Restore defaults" button and make sure you're able to download files from GitHub release?

**Comment by tripple626** [comment]
> Have you click the "Restore defaults" button and make sure you're able to download files from GitHub release?

**Yes, I have, but I must enable Wiktionary first. Then, I can try clicking the "Restore Defaults" button. However, the result showed error messages during the file download. If I disable Wiktionary, I cannot access the window that contains the "Restore Defaults" button.**

**here is error massage (enabled wiktionary) :** 
calibre, version 7.26.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Downloading Word Wise file 
Job: "Downloading Word Wise file" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.deps", line 165, in download_word_wise_file
    tar_f.extractall(download_folder)
  File "tarfile.py", line 2264, in extractall
  File "tarfile.py", line 2327, in _extract_one
  File "tarfile.py", line 2410, in _extract_member
  File "tarfile.py", line 2463, in makefile
  File "tarfile.py", line 252, in copyfileobj
  File "bz2.py", line 164, in read
  File "_compression.py", line 68, in readinto
  File "_compression.py", line 99, in read
EOFError: Compressed file ended before the end-of-stream marker was reached
 
Called with args: (True, 'en', {'add_locator_map': False, 'gloss_lang': 'en', 'mediawiki_api': '', 'minimal_x_ray_count': 1, 'model_size': 'md', 'python_path': '', 'remove_link_styles': False, 'search_people': False, 'show_change_kindle_ww_lang_warning': False, 'use_wiktionary_for_kindle': True, 'zh_wiki_variant': 'cn'}) {'notifications': <queue.Queue object at 0x1274c5e10>, 'abort': <threading.Event at 0x1274c4cd0: unset>, 'log': <calibre.utils.logging.GUILog object at 0x1274c7650>} 


**here is error massage (disable wiktionary) :** 

calibre, version 7.26.0
ERROR: Unhandled exception: <b>DatabaseError</b>:database disk image is malformed

calibre 7.26  embedded-python: True
macOS-15.3.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '24.3.0', 'Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:06 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('15.3.2', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: WordDumb (3, 33, 2)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.config", line 240, in open_choose_lemma_lang_dialog
    custom_lemmas_dlg = CustomLemmasDialog(
                        ^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.worddumb.custom_lemmas", line 70, in __init__
    self.init_sql_table(is_kindle)
  File "calibre_plugins.worddumb.custom_lemmas", line 87, in init_sql_table
    self.check_empty_kindle_gloss()
  File "calibre_plugins.worddumb.custom_lemmas", line 196, in check_empty_kindle_gloss
    for (gloss,) in custom_db_conn.execute("SELECT short_def FROM senses LIMIT 1"):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.DatabaseError: database disk image is malformed

**Comment by xxyzz** [comment]
Delete "worddumb-lemmas" folder in calibre plugin folder. I think the error message indicates you can't download file from GitHub, check your network.
