### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by sagebei** [xxyzz/WordDumb#269]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I was using python 3.12.2 and got this error message while trying to create the word-wise for a mobi book. 

calibre, version 7.20.0 (linux, embedded-python: True)
Outdated Python: Your Python version is too old, please update to a newer version and read the document for more information.

### Plugin settings and reproduce steps

As a matter of fact, I could not get this plugin working on any of my machines. It stoped at errors like spacy installation error, could not find python error.

**Comment by sagebei** [comment]
Can I run this from a terminal, not as a plugin?

**Comment by xxyzz** [comment]
Sounds like environment issue(`python3` command should in `PATH`), you can set python binary path manually in the plugin settings.

The program could run in terminal but as a calibre plugin: `calibre-debug -r WordDumb -- -h`

**Comment by sagebei** [comment]
Thank you! Adding the python path solved this issue.
