### ISSUE TITLE
Issue with macbook sequoia 15.1

### ISSUE THREAD

**Issue by Maximummmmm** [xxyzz/WordDumb#275]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/Python.h won't be automatically included in the manifest: the path must be relative
            dependency /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/pythread.h won't be automatically included in the manifest: the path must be relative
            reading manifest file 'srsly.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no files found matching '*.pxd' under directory 'srsly'
            adding license file 'LICENSE'
            writing manifest file 'srsly.egg-info/SOURCES.txt'
            /private/var/folders/f7/099f8lys7n95tkrvvl5_nhrr0000gn/T/pip-build-env-vm1ewlqf/overlay/lib/python3.13/site-packages/setuptools/command/build_py.py:219: _Warning: Package 'srsly.ujson.lib' is absent from the `packages` configuration.
            !!
      
                    ********************************************************************************
                    ############################
                    # Package would be ignored #
                    ############################
                    Python recognizes 'srsly.ujson.lib' as an importable package[^1],
                    but it is absent from setuptools' `packages` configuration.
      
                    This leads to an ambiguous overall configuration. If you want to distribute this
                    package, please make sure that 'srsly.ujson.lib' is explicitly added
                    to the `packages` configuration field.
      
                    Alternatively, you can also rely on setuptools' discovery methods
                    (for example by using `find_namespace_packages(...)`/`find_namespace:`
                    instead of `find_packages(...)`/`find:`).
      
                    You can read more about "package discovery" on setuptools documentation page:
      
                    - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
                    If you don't want 'srsly.ujson.lib' to be distributed and are
                    already explicitly excluding 'srsly.ujson.lib' via
                    `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
                    you can try to use `exclude_package_data`, or `include-package-data=False` in
                    combination with a more fine grained `package-data` configuration.
      
                    You can read more about "package data files" on setuptools documentation page:
      
                    - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
                    [^1]: For Python, any directory (with suitable naming) can be imported,
                          even if it does not contain any `.py` files.
                          On the other hand, currently there is no concept of package data
                          directory, all directories are treated like packages.
                    ********************************************************************************
      
            !!
              check.warn(importable)
            copying srsly/ujson/JSONtoObj.c -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson
            copying srsly/ujson/objToJSON.c -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson
            copying srsly/ujson/py_defines.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson
            copying srsly/ujson/ujson.c -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson
            copying srsly/ujson/version.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson
            creating build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson/lib
            copying srsly/ujson/lib/dconv_wrapper.cc -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson/lib
            copying srsly/ujson/lib/ultrajson.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson/lib
            copying srsly/ujson/lib/ultrajsondec.c -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson/lib
            copying srsly/ujson/lib/ultrajsonenc.c -> build/lib.macosx-15.0-arm64-cpython-313/srsly/ujson/lib
            copying srsly/msgpack/_packer.cpp -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/_packer.pyx -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/_unpacker.cpp -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/_unpacker.pyx -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/buff_converter.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/pack.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/pack_template.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/sysdep.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/unpack.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/unpack_define.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/msgpack/unpack_template.h -> build/lib.macosx-15.0-arm64-cpython-313/srsly/msgpack
            copying srsly/tests/ujson/334-reproducer.json -> build/lib.macosx-15.0-arm64-cpython-313/srsly/tests/ujson
            running build_ext
            building 'srsly.msgpack._unpacker' extension
            creating build/temp.macosx-15.0-arm64-cpython-313/srsly/msgpack
            clang++ -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -D__LITTLE_ENDIAN__=1 -Isrsly/msgpack -I/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13 -I. -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c srsly/msgpack/_unpacker.cpp -o build/temp.macosx-15.0-arm64-cpython-313/srsly/msgpack/_unpacker.o -O2 -Wno-strict-prototypes -Wno-unused-function
            srsly/msgpack/_unpacker.cpp:877:59: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
              877 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u) {
                  |                                                           ^
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
               10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
                  | ^
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
              251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                  |                                                      ^
            srsly/msgpack/_unpacker.cpp:878:11: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
              878 |     const Py_UNICODE *u_end = u;
                  |           ^
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
               10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
                  | ^
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
              251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                  |                                                      ^
            srsly/msgpack/_unpacker.cpp:2605:17: error: use of undeclared identifier 'PyObject_AsReadBuffer'; did you mean 'PyObject_GetBuffer'?
             2605 |     __pyx_t_2 = PyObject_AsReadBuffer(__pyx_v_obj, ((void const **)__pyx_v_buf), __pyx_v_buffer_len); if (unlikely(__pyx_t_2 == ((int)-1))) __PYX_ERR(0, 136, __pyx_L1_error)
                  |                 ^~~~~~~~~~~~~~~~~~~~~
                  |                 PyObject_GetBuffer
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/pybuffer.h:46:17: note: 'PyObject_GetBuffer' declared here
               46 | PyAPI_FUNC(int) PyObject_GetBuffer(PyObject *obj, Py_buffer *view,
                  |                 ^
            srsly/msgpack/_unpacker.cpp:2605:52: error: cannot initialize a parameter of type 'Py_buffer *' with an rvalue of type 'const void **'
             2605 |     __pyx_t_2 = PyObject_AsReadBuffer(__pyx_v_obj, ((void const **)__pyx_v_buf), __pyx_v_buffer_len); if (unlikely(__pyx_t_2 == ((int)-1))) __PYX_ERR(0, 136, __pyx_L1_error)
                  |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/pybuffer.h:46:62: note: passing argument to parameter 'view' here
               46 | PyAPI_FUNC(int) PyObject_GetBuffer(PyObject *obj, Py_buffer *view,
                  |                                                              ^
            srsly/msgpack/_unpacker.cpp:9638:27: error: no matching function for call to '_PyLong_AsByteArray'
             9638 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
                  |                           ^~~~~~~~~~~~~~~~~~~
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: candidate function not viable: requires 6 arguments, but 5 were provided
              111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                  |                 ^                   ~~~~~~~~~~~~~~~~
              112 |     unsigned char* bytes, size_t n,
                  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              113 |     int little_endian, int is_signed, int with_exceptions);
                  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            srsly/msgpack/_unpacker.cpp:9834:27: error: no matching function for call to '_PyLong_AsByteArray'
             9834 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
                  |                           ^~~~~~~~~~~~~~~~~~~
            /opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: candidate function not viable: requires 6 arguments, but 5 were provided
              111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                  |                 ^                   ~~~~~~~~~~~~~~~~
              112 |     unsigned char* bytes, size_t n,
                  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              113 |     int little_endian, int is_signed, int with_exceptions);
                  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            2 warnings and 4 errors generated.
            error: command '/usr/bin/clang++' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for srsly
      Failed to build thinc srsly
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (thinc, srsly)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Plugin settings and reproduce steps

Hi there,

I have an issue using Worddumb with python 3.12.0

Both calibre and the plugin are updated. 

Thank you for helping.

**Comment by xxyzz** [comment]
You're using Python 3.13, please downgrade to 3.12. You could set the Python binary path manually in the plugin settings window.

**Comment by Maximummmmm** [comment]
Thank you so much!!
