### ISSUE TITLE
Saving customized lemmas is not transferable to the Kindle

### ISSUE THREAD

**Issue by BasilPadre** [xxyzz/WordDumb#278]
### Checkboxes

- [x] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

calibre, version 7.22.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Saving customized lemmas 
Job: "Saving customized lemmas" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.config", line 321, in dump_lemmas_job
  File "calibre_plugins.worddumb.deps", line 42, in install_deps
  File "calibre_plugins.worddumb.deps", line 134, in pip_install
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\Basil\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.13', '--no-user', '--no-cache-dir', 'spacy==3.8.2']' returned non-zero exit status 1.
 
Called with args: (True, WindowsPath('C:/Users/Basil/AppData/Roaming/calibre/plugins/worddumb-lemmas/wiktionary_en_en_v0.db'), 'en') {'notifications': <queue.Queue object at 0x00000228B91A1350>, 'abort': <threading.Event at 0x228b91f4fd0: unset>, 'log': <calibre.utils.logging.GUILog object at 0x00000228BDEE2AD0>} 
  error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [111 lines of output]
  Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
  Collecting setuptools
    Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
  Collecting cython<3.0,>=0.25
    Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.10-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
  Collecting preshed<3.1.0,>=3.0.2
    Using cached preshed-3.0.9.tar.gz (14 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached murmurhash-1.0.11-cp313-cp313-win_amd64.whl.metadata (2.0 kB)
  Collecting thinc<8.4.0,>=8.3.0
    Using cached thinc-8.3.2.tar.gz (193 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    error: subprocess-exited-with-error
  
    pip subprocess to install build dependencies did not run successfully.
    exit code: 1
  
    [73 lines of output]
    Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
    Collecting setuptools
      Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
    Collecting cython<3.0,>=0.25
      Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
    Collecting murmurhash<1.1.0,>=1.0.2
      Using cached murmurhash-1.0.11-cp313-cp313-win_amd64.whl.metadata (2.0 kB)
    Collecting cymem<2.1.0,>=2.0.2
      Using cached cymem-2.0.10-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
    Collecting preshed<3.1.0,>=3.0.2
      Using cached preshed-3.0.9.tar.gz (14 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting blis<1.1.0,>=1.0.0
      Using cached blis-1.0.1.tar.gz (3.6 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting numpy<2.1.0,>=2.0.0
      Using cached numpy-2.0.2.tar.gz (18.9 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error
  
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
  
      [21 lines of output]
      + C:\Users\Basil\AppData\Local\Programs\Python\Python313\python.exe C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9\vendored-meson\meson\meson.py setup C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9 C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9\.mesonpy-soyj0wpo -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9\.mesonpy-soyj0wpo\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.99
      Source dir: C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9
      Build dir: C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9\.mesonpy-soyj0wpo
      Build type: native build
      Project name: NumPy
      Project version: 2.0.2
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
  
      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"
  
      A full log can be found at C:\Users\Basil\AppData\Local\Temp\pip-install-e05g0kg8\numpy_c81ae829169447fbaacf939aad59f6b9\.mesonpy-soyj0wpo\meson-logs\meson-log.txt
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
  
    Encountered error while generating package metadata.
  
    See above for output.
  
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Plugin settings and reproduce steps

1. Go to WordDumb Preferences
2. Select Customise Kindle Word Wise
3. Select Book Language → English
4. I agree to the data transfer
5. An error occurs during the transfer process

**Comment by xxyzz** [comment]
Python 3.13 is not supported, please use 3.12.
