### ISSUE TITLE
help, already install latest calibre, worddumb, pyhton

### ISSUE THREAD

**Issue by kasogiak92** [xxyzz/WordDumb#279]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

Starting job: Generating Word Wise and X-Ray for The Boyfriend: A Psychological Thriller 
Job: "Generating Word Wise and X-Ray for The Boyfriend: A Psychological Thriller" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 177, in do_job
  File "calibre_plugins.worddumb.deps", line 42, in install_deps
  File "calibre_plugins.worddumb.deps", line 134, in pip_install
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\JABPATSIP\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.13', '--no-user', '--no-cache-dir', 'spacy==3.8.2']' returned non-zero exit status 1.

 full log can be found at C:\Users\JABPATSIP\AppData\Local\Temp\pip-install-2pi9accn\numpy_ca97f7ec6cae4ee1bf437cf3e045df40\.mesonpy-p6wxsb0z\meson-logs\meson-log.txt
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
  
    Encountered error while generating package metadata.
  
    See above for output.
  
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Plugin settings and reproduce steps

install worddumb done, python done

### Generated files, screenshots or videos

![asdasda](https://github.com/user-attachments/assets/45204120-8aa0-48fe-8c98-cad6f2b7e711)

**Comment by xxyzz** [comment]
Python 3.13 is not supported, please use 3.12.

**Comment by kasogiak92** [comment]
okay, i just figured it out
Thanks alot
