### ISSUE TITLE
Can't generate xray on a book I downloaded

### ISSUE THREAD

**Issue by ezxpro** [xxyzz/WordDumb#31]
### Describe the bug

I tried to Generate X-Ray and Wordwise for a book, a bug happened and it didn't succet.

### System Information

OS: Windows 11 21H2 x64
Calibre version: 5.41, 64bit
Python version: 3.10.4, 64bit
Plugin version: 3.19.0

### Error message

```text
calibre, version 5.41.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub. 

Starting job: Generating X-Ray for The Intelligent Investor, Rev. Ed: The Definitive Book on Value Investing 
Job: "Generating X-Ray for The Intelligent Investor, Rev. Ed: The Definitive Book on Value Investing" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 101, in do_job
  File "calibre_plugins.worddumb.parse_job", line 197, in create_files
  File "calibre_plugins.worddumb.x_ray_epub", line 126, in modify_epub
  File "calibre_plugins.worddumb.x_ray_epub", line 238, in zip_extract_folder
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 610, in _rmtree_unsafe
  File "shutil.py", line 619, in _rmtree_unsafe
  File "shutil.py", line 617, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'X:\\#Others\\Calibre_Data\\Biblioteca\\Benjamin Graham\\The Intelligent Investor, Rev. Ed_ (512)\\extract\\META-INF'
 
Called with args: ((512, 'EPUB', 'X:\\#Others\\Calibre_Data\\Biblioteca\\Benjamin Graham\\The Intelligent Investor, Rev. Ed_ (512)\\The Intelligent Investor, Rev. - Benjamin Graham.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000151D4A53250>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x00000151D4A53460>, 'abort': <threading.Event object at 0x00000151D4A535E0>, 'log': <calibre.utils.logging.GUILog object at 0x00000151D4A53790>}
```

### Reproduce steps

1. Download this book https://libgen.rocks/ads.php?md5=4E11C78A1F1B15126DC967F34751B72D
2. add it to calibre library
3. In WordDumb, click "create X-Ray and WordWise

**Comment by xxyzz** [comment]
The new EPUB file with x-ray footnotes was created before the error, you could ignore this error and delete the `extract` folder manually. I'm not sure what causes the permission error, maybe it's virus scanner opens the file at the same time.

**Comment by ezxpro** [comment]
> The new EPUB file with x-ray footnotes was created before the error, you could ignore this error and delete the `extract` folder manually. I'm not sure what causes the permission error, maybe it's virus scanner opens the file at the same time.

Well, I  deleted all the data and tried again, ran just fine this time.
I'm closing this issue, thanks for the support.
