### ISSUE TITLE
X-Ray footnotes for EPUB: Option to unconditionally create them

### ISSUE THREAD

**Issue by Philantrop** [xxyzz/WordDumb#32]
Right now, X-Ray footnotes for EPUB books are only created if EPUB is the **only** format. Usually, though, I keep EPUB and KFX (at least) versions of all my ebooks. (I use both KOReader which consumes EPUB and Kindles (KFX).)

Thus, it would be useful if the plugin had an option to unconditionally create the new EPUB with X-Ray footnotes.

**Comment by xxyzz** [comment]
I add a new option to set preferred book format order(https://github.com/xxyzz/WordDumb/commit/9768067d328ca2a76bc6504d1f9e3333c396f6bb), you can download the test version from [GitHub Actions artifact](https://github.com/xxyzz/WordDumb/actions/runs/2402962790).

**Comment by Philantrop** [comment]
Thanks, that works. I can now first set the order to EPUB and KFX, generate the EPUB, switch the order and then generate the "native" X-Ray file. 
Maybe checkboxes instead of ordering would allow for easier handling? Ideally allowing me to generate both EPUB and native X-Ray in one go?

**Comment by xxyzz** [comment]
I add another option "create files for all available formats" in https://github.com/xxyzz/WordDumb/commit/06556378bdc743889c7fdeae75002f9aa5997e9d

**Comment by Philantrop** [comment]
Thank you very much! That's perfect!
