### ISSUE TITLE
No Wordwise with abnormal: sqlite3.OperationalError

### ISSUE THREAD

**Issue by Caesar997788** [xxyzz/WordDumb#37]
### Describe the bug

The wordwise feature of the plugin cannot work with an abnormal 'sqlite3.OperationalError: no such table'

### System Information

OS: MacOS Monterey 12.4
calibre, version: 5.44.0
python verion: 3.9
plugin version: 3.21.2

### Error message

```text
错误： 未处理的异常: <b>OperationalError</b>:no such table: lemmas

calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: zh_CN
Successfully initialized third party plugins: WordDumb (3, 21, 2)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.config", line 170, in open_custom_lemmas_dialog
    custom_lemmas_dlg = CustomLemmasDialog(self)
  File "calibre_plugins.worddumb.custom_lemmas", line 31, in __init__
    self.lemmas_model = LemmasTableModle()
  File "calibre_plugins.worddumb.custom_lemmas", line 79, in __init__
    for (lemma, sense_id, short_def, full_def) in klld_conn.execute(
sqlite3.OperationalError: no such table: lemmas
```

### Reproduce steps

1. Connect Kindle
2. Go to 'Calibre", pick an AZW3
3. Click on 'WordDumb' to create WordWise and no task is added
4. Open the preference of WordDumb, and click on 'Customize Word Wise lemmas' -- An error occurs.

**Comment by xxyzz** [comment]
Maybe the Word Wise database file(`WordWise.kll.en.en.db` or `kll.en.en.klld`) in `~/Library/Preferences/calibre/plugins/worddumb-lemmas` is corrupted somehow. Delete that file then connect your device and try again. The database file size should be 19MB.

**Comment by Caesar997788** [comment]
I only found a ` CC-CEDICT.cn-kll.zh.pn.klld ` in the folder, it's 13.3MB. If I delete it, the file will be generated again.
The book language is actually English.

**Comment by Caesar997788** [comment]
I only found a CC-CEDICT.cn-kll.zh.pn.klld in the folder, it's 13.3MB. If I delete it, the file will be generated again.
The book language is actually English.

**Comment by Caesar997788** [comment]
I only found a CC-CEDICT.cn-kll.zh.pn.klld in the folder, it's 13.3MB. If I delete it, the file will be generated again.
The book language is actually English.

**Comment by xxyzz** [comment]
Your device doesn't have the Word Wise database file, you can download it from Amazon by open a Word Wise enabled book and https://github.com/xxyzz/WordDumb/commit/b5b8e46d7f6cd4c885f2eb5691a1df7b7dd35e32 should fix this error.

**Comment by Caesar997788** [comment]
I found a [WordWise.kll.en.en.db](https://github.com/xnohat/wordwise-dict/blob/master/WordWise.kll.en.en.db) in github and it worked well. I can customize Word Wise lemmas now but the task cannot be added. I deleted the AZW3 and it's folder ending with `.sdr` files both in kindle and calibre and do it again, the task still couldn't be added.

**Comment by xxyzz** [comment]
Please check the book language by right click the book then click "Edit metadata". If the "Languages" data contains "English" and the plugin still can't create Word Wise file, please upload the book file.

**Comment by Caesar997788** [comment]
Alright, the feature functions well now, thank you.
