### ISSUE TITLE
Nonsense error message appears generating only X-Ray

### ISSUE THREAD

**Issue by Phobooky** [xxyzz/WordDumb#47]
Wonderful plugin. More than expected. When generating X-Ray in Spanish (Create X-Ray option), it does work perfectly, but a nonsense error message appears. It says:
Non-English book: For Kindle format books, Word Wise is only available in books in English.
I'm not traying to generate Word Wise, only X-Ray. I think this message should not appear in this menu option.

**Comment by xxyzz** [comment]
Thanks for your report, fixed in https://github.com/xxyzz/WordDumb/commit/9e6b257f2f559cc714f8078880740ca66708a917.
