### ISSUE TITLE
X-Ray not showing characters description but only a quote.

### ISSUE THREAD

**Issue by steakhutzeee** [xxyzz/WordDumb#5]
Hi,

as mentioned on the forums i have an issue with the WordDumb plugin.

It generates the word wise and x-ray but the x-ray is not working properly. I tried with 2 books and i have the same outcome on both.

I will attach one of the books. Had to zip it to be able to upload.

What happens is that when i select a character x-ray only displays a quote for it from the book and not the description for the character.

Will also attach a screenshot from my Kindle Paperwhite.
![img1](https://user-images.githubusercontent.com/57228102/123549065-b13b7800-d767-11eb-808a-d5b57a22766f.jpg)

Thanks in advance!

**Comment by xxyzz** [comment]
All descriptions come from Wikipedia. This plugin doesn't know whether you're reading a nonfiction or not, so only terms are searched on Wikipedia. You might find a Wikipedia page for a famous fictional character but that's rare.

**Comment by steakhutzeee** [comment]
> 
> 
> All descriptions come from Wikipedia. This plugin doesn't know whether you're reading a nonfiction or not, so only terms are searched on Wikipedia. You might find a Wikipedia page for a famous fictional character but that's rare.

I see, thanks. So basically there is nothing that can be done.

**Comment by xxyzz** [comment]
Right, unless some websites can provide that information.

**Comment by steakhutzeee** [comment]
> Right, unless some websites can provide that information.

Well actually there is a Fandom wiki https://mistborn.fandom.com/wiki/Vin

Of course there are also other characters there.

Don't know if it can be added as a source, maybe not directly this one but fandom wikis in general.

**Comment by xxyzz** [comment]
Sadly, fandom uses MediaWiki 1.33.3 which lacks [the TextExtracts extension](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:TextExtracts), it's required to get the first section of a page as X-Ray description.

**Comment by steakhutzeee** [comment]
> 
> 
> Sadly, fandom uses MediaWiki 1.33.3 which [lacks](https://mistborn.fandom.com/api.php?action=help&modules=query) the [TextExtracts extension](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:TextExtracts), it's required to get the first section of a page as X-Ray description.

From the link i see that MediaWiki supports TextExtracts extension since version 1.23+. But you know more for sure.

**Comment by xxyzz** [comment]
The top of the page says "This extension comes with MediaWiki 1.34 and above. Thus you do not have to download it again." and the fandom api doesn't have the `extracts` parameter: https://mistborn.fandom.com/api.php?action=query&prop=extracts&exintro&titles=Vin

**Comment by steakhutzeee** [comment]
> The top of the page says "This extension comes with MediaWiki 1.34 and above. Thus you do not have to download it again." and the fandom api doesn't have the `extracts` parameter: https://mistborn.fandom.com/api.php?action=query&prop=extracts&exintro&titles=Vin

I could be wrong but actually clicking on the link i can see the extracts parameter available. This is also true for a character of a book i'm actually reading [https://stormlightarchive.fandom.com/api.php?action=query&prop=extracts&exintro&titles=Gavilar_Kholin](https://stormlightarchive.fandom.com/api.php?action=query&prop=extracts&exintro&titles=Gavilar_Kholin)

Maybe something changed on Fandom side?

**Comment by xxyzz** [comment]
They added the extension a few months ago. I can add an option in setting to set the Wiki link. But some pages will return an empty string because the first paraphrase doesn't contain any text.

**Comment by steakhutzeee** [comment]
> They added the extension a few months ago. I can add an option in setting to set the Wiki link. But some pages will return an empty string because the first paraphrase doesn't contain any text.

Thank you very much!!

**Comment by xxyzz** [comment]
v3.18.0 adds support of Fandom.
