### ISSUE TITLE
Use other dictionaries instead of Wiktionary for word wise

### ISSUE THREAD

**Issue by woaidangyang** [xxyzz/WordDumb#51]
The newly added feature that adds word wise to epubs is great!

Since the quality of Wiktionary is relatively low sometimes, I'm wondering if it's possible to use some customized dictionaries for word wise. A good example is this plugin for Anki: https://github.com/sth2018/FastWordQuery

Another request is if WordDumb can support "fuzzy query", meaning that it would hit the word with different forms.

It might be too much to ask! Thank you so much!

**Comment by xxyzz** [comment]
Support of new dictionary file format may not be very hard but extract short glosses from a dictionary requires some work.

For Kindle Word Wise, I use [LemmInflect](https://github.com/bjascob/LemmInflect) to inflect each lemma: [code](https://github.com/xxyzz/WordDumb/blob/master/data/dump_lemmas.py)

For EPUB, the `forms` data from Wiktionary are used.

**Comment by woaidangyang** [comment]
Got it. Thank you!

I agree with you that it might not be possible to extract short glosses from some of the dictionaries. But it would already be a huge help if I can highlight the words that I want to learn in the book and have their explanations available a click away.

**Comment by xxyzz** [comment]
Wiktionary has much more potential to explore. Once I figure out how to use https://github.com/tatuylonen/wiktextract to extract non-English Wiktionary dump files, it'll be possible to have glosses in many languages.
