### ISSUE TITLE
Add pronunciations into the Wiktionary explanations

### ISSUE THREAD

**Issue by woaidangyang** [xxyzz/WordDumb#56]
Would it be possible to add pronunciations (such as IPA /sliːp/ for sleep) into the explanations?

Thank you so much!

**Comment by xxyzz** [comment]
Hi @woaidangyang, I have added the feature to the master branch.

**Comment by woaidangyang** [comment]
Thank you so much!

**Comment by xxyzz** [comment]
I forget to say you'll need to delete the old `wiktionary_*` files from the `worddumb-lemmas` folder(it's inside the calibre plugin folder).

**Comment by xxyzz** [comment]
I'm able to fix the first case. Please check out the latest commit, I also added some other improvements. Old Wiktionary files need to be deleted.

"subjectivity" is not an inflected word, you could edit the gloss in the customize Wiktionary dialog. Even better, you could edit the definition on Wiktionary so others can benefit from your contribution.

**Comment by woaidangyang** [comment]
It's working! Super! Thank you so much!
