### ISSUE TITLE
No module named 'click._bashcomplete'

### ISSUE THREAD

**Issue by DorBreger** [xxyzz/WordDumb#6]
Hello, i use calibre 5.22.1 on arch linux (installed through pacman).
I tried creating an x-ray file for an epub file I had converted to AZW3. 
here is the relevant part of the calibre log
[calibre-log.txt](https://github.com/xxyzz/WordDumb/files/6768816/calibre-log.txt)

**Comment by xxyzz** [comment]
Don't change the plugin configuration, restart calibre should fix this.

**Comment by DorBreger** [comment]
same error comes up after I restarted calibre

**Comment by DorBreger** [comment]
I should mention that I recently installed the plugin (version 3.9.2) through the calibre interface.

**Comment by xxyzz** [comment]
What's the output of these commands?

```
$ ls .config/calibre/plugins/worddumb-libs
$ ls .config/calibre/plugins/worddumb-libs/click_7.1.2/click
$ cat .config/calibre/plugins/worddumb.json
```

**Comment by DorBreger** [comment]
I executed them by order.
[commands.txt](https://github.com/xxyzz/WordDumb/files/6769889/commands.txt)

**Comment by xxyzz** [comment]
I'm not sure what's going on here... I only encounter the error once then it never occurs. How did you reliably produce this error?

**Comment by DorBreger** [comment]
I simply installed the plugin from the calibre interface. I didn't do anything unusual.

**Comment by DorBreger** [comment]
I tried reinstalling calibre and the plugin and the error persists/

**Comment by xxyzz** [comment]
```
$ rm -rf .config/calibre/plugins/worddumb-libs
```

Try this command to reinstall the packages, not sure if this helps.

**Comment by DorBreger** [comment]
this time instead of giving the error outright, the job ran for a one minute and 22 seconds.
I'm attaching the error message I got, but I think it's identical. 
[error.txt](https://github.com/xxyzz/WordDumb/files/6770342/error.txt)

**Comment by xxyzz** [comment]
Do you have a newer version of 'click'(>= 8) installed in your system?

**Comment by DorBreger** [comment]
`$ pip show  click` says it's 8.0.1
I tried  `import click` in the calibre-debug terminal and it worked, but  `import._bashcomplete` didn't.

**Comment by xxyzz** [comment]
spacy(infect it's typer) requires older version of click, try this version:

[worddumb.zip](https://github.com/xxyzz/WordDumb/files/6770443/worddumb.zip)

**Comment by DorBreger** [comment]
thank you this seems to work, as no error comes up, but I emailed the .mobi file to my kindle with the .asc file and it doesn't seem to have x-ray, what could be the cause? Unfortunately I can't transfer the files using USB since I'm traveling and forgot an appropriate cable.

**Comment by DorBreger** [comment]
or am I supposed to use the plugin itself to send the books to the Kindle?

**Comment by xxyzz** [comment]
Plug Kindle to your pc then click the plugin menu. I don't think Amazon will email these files.
