### ISSUE TITLE
Ocurrence of words in X-Ray are not found in KFX format

### ISSUE THREAD

**Issue by Phobooky** [xxyzz/WordDumb#64]
### Describe the bug

I've detected that sometimes there are words included in X-Ray asc file generated by the plugin that are not found when you look for it in a KFX book. 
I enclose an example. The book and the generated ASC file.
Looking inside the ASC file, the word "catafracto" has only one ocurrence, but actually there are a lot of them.
 

### System Information

OS: windows 11
All last versions.

### Error message

```text
No error message
```

### Reproduce steps

Double tap in "catagfracto" word

### Screenshots or videos

![image](https://user-images.githubusercontent.com/24461946/186935134-5e6edd8e-6ab1-4754-a7d0-cbdad7b6a6b3.png)
![image](https://user-images.githubusercontent.com/24461946/186935181-71085ebb-e791-437c-b285-f05c306a04fb.png)
[Posteguillo, Santiago.zip](https://github.com/xxyzz/WordDumb/files/9434310/Posteguillo.Santiago.zip)

**Comment by xxyzz** [comment]
spaCy probably marked that word as person by mistake in that particular sentence, the word means "cataphract" which shouldn't be marked as person or term. You can use the custom X-Ray feature to ignore this word.

**Comment by Phobooky** [comment]
You're completement right and the fault was me. I was using the custom X-Ray feature and I made a mistake. I assigned to "catafracto" the property "PERSON".  As there are only one occurrence in singular, the behabiour seems correct. To be sure, I've changed the word to "PRODUCT" and I have generated again the file. But the result is not good. The problem remains. There are a lot of occurrences of the word in the book and only three are located:

![image](https://user-images.githubusercontent.com/24461946/187020939-29eb1f65-fb37-40f4-8d93-87a4b8c7a187.png)

If I delete this word from custom X-Ray feature the result is:

![image](https://user-images.githubusercontent.com/24461946/187021004-59f4e412-7aeb-44fc-bad9-cc930e1e1a18.png)

If I change the word in custom X-Ray feature writing the plural one, it locate all of the ocurrences.

![image](https://user-images.githubusercontent.com/24461946/187021191-5c37b161-7998-43d1-81a0-c445efd16f71.png)

I don't know why, but the plugin part of code to locate occurrences of this word is not working, but the plural.

**Comment by xxyzz** [comment]
You want to add the word "catafracto" and "catafractos" as a X-Ray entity? You can create a custom X-Ray data and add the plural form to the "Aliases" input box. spaCy entity ruler can only find the exact matched string, and custom X-Ray names are not fuzz matched, so you have to add the precise strings you want to find.

**Comment by Phobooky** [comment]
Yes, I want to add the word "catafracto" and "catafractos" as a X-Ray entity. I known about the alias, but I supposed that the plugin looked for the word and plural ones from it. It was my fault. Sorry. Now, I understand perfectly the way of work. 
But I think a stange behavour remains.
If I delete "catafracto" from the custom list,  spaCy locate "catafractos", but only two ocurrences. It should find 22 ocurrences.
Do you know why?
![image](https://user-images.githubusercontent.com/24461946/187024793-7ed11194-3948-489e-b51c-89a798abef4d.png)

**Comment by xxyzz** [comment]
spaCy can't guarantee to find the same word in every sentences, unless you add that word to the entity ruler via the custom X-Ray dialog. Other NLP software should be the same.

**Comment by Phobooky** [comment]
Ok. Thanks for your help and the explanations given. In base the spaCy  is the tool used by the plugin, I think yo can close the issue.

**Comment by xxyzz** [comment]
OK, I'll close the issue now.
