### ISSUE TITLE
WinError 2 The System cannot find the file specified

### ISSUE THREAD

**Issue by Taubin** [xxyzz/WordDumb#65]
### Describe the bug

When attempting to use worddumb on any epub file in Windows 10 x64, calibre 6.3 worddumb 3.25.0, I get an error stating the system cannot find the file specified. 

Worddumb does create the file, and I have tried running as admin just in case it's a permission issue. I also moved my library to a new location, and the issue persists. 

![image](https://user-images.githubusercontent.com/8891792/186991939-42a8ffa2-a8d5-4cd1-ab70-eca527af336d.png)

### System Information

OS: Windows 10 X64
Calibre version: 6.3 64 bit
Python version: 3.10
Plugin version: 3.25.0

### Error message

```text
[WinError 2] The system cannot find the file specified: 'Dragon on a Pedestal - Piers Anthony_x_ray_word_wise.epub'

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 88, in run
  File "calibre\gui2\device.py", line 620, in _upload_books
  File "calibre\devices\usbms\driver.py", line 323, in upload_books
  File "calibre\devices\usbms\device.py", line 827, in _sanity_check
  File "calibre\devices\utils.py", line 32, in sanity_check
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Dragon on a Pedestal - Piers Anthony_x_ray_word_wise.epub'
```

### Reproduce steps

Add book
Edit metadata to include the amazon ASIN: B000FBFOFA
Connect kindle
Click WordDumb
WordDumb creates the x-ray file and throws the error

**Comment by Taubin** [comment]
This seems to be happening with epub files, but if I convert them to azw3, it uploads to the kindle just fine.

**Comment by xxyzz** [comment]
Kindle doesn't support EPUB, I never though anyone would send an EPUB file to Kindle. I'll add a warning dialog later.

**Comment by Taubin** [comment]
Oh that makes sense, sorry about that. I had read they've added support for epub but it doesn't look like it's been fully implemented by amazon yet. 

Sorry about that!

**Comment by xxyzz** [comment]
Amazon only support sending EPUB to Kindle as personal document via email, the file format is converted by Amazon. Kindle still can't read EPUB files natively and personal document doesn't support X-Ray and Word Wise.
