### ISSUE TITLE
Leaving out simpler words in epub Word Wise

### ISSUE THREAD

**Issue by Vuizur** [xxyzz/WordDumb#72]
I don't want to be annoying by suggesting even more features, so feel free to ignore this, but have you thought about using something like the [wordfreq library](https://github.com/rspeer/wordfreq) to allow the user to set the minimum difficulty of looked up words? So that only the more difficult words get translated.

**Comment by xxyzz** [comment]
Thanks for your suggestion! I add default difficulty to three languages, the code is at here: https://github.com/xxyzz/Proficiency

I'll use wordfreq for other languages until better data source could be found.

**Comment by xxyzz** [comment]
The feature has been implemented, you can test it by downloading the plugin zip file from GitHub Actions artifacts.

**Comment by Vuizur** [comment]
Awesome!

**Comment by xxyzz** [comment]
All languages have default difficulty since version 3.26.0, close the issue now.
