### ISSUE TITLE
German books can't be generated

### ISSUE THREAD

**Issue by Humam-Hamdan** [xxyzz/WordDumb#73]
### Describe the bug

it says that it can't generate wordwise / x-ray for azw3 + kfx

### System Information

Windows 10 x64
Calibre 6.4
Python 3.10.3
Plugin 3.25.1

### Error message

```text
calibre, version 6.3.0
Non-English book: For Kindle format books, Word Wise is only available in books in English.
```

### Reproduce steps

1. download a german book (harry potter 7)
2. press on word dump

**Comment by xxyzz** [comment]
Kindle only support Word Wise for English books, X-Ray and EPUB books don't have this limitation.

**Comment by Humam-Hamdan** [comment]
OH, ok, thanks.
