### ISSUE TITLE
cannot use it to send to android devices.

### ISSUE THREAD

**Issue by monkeychenh** [xxyzz/WordDumb#75]
### Describe the bug

ERROR: Unhandled exception: <b>TypeError</b>:SendFile.push_files_to_android() missing 1 required positional argument: 'package_name'

### System Information

calibre, version 6.6.1
macOS

### Error message

```text
calibre 6.6.1  embedded-python: True
macOS-12.4-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && WordDumb (3, 25, 1)
Traceback (most recent call last):
  File "calibre/gui2/__init__.py", line 716, in dispatch
  File "calibre_plugins.worddumb.ui", line 142, in done
    SendFile(gui, job.result, package_name, notif).send_files(None)
  File "calibre_plugins.worddumb.send_file", line 44, in send_files
    self.push_files_to_android(adb_path)
TypeError: SendFile.push_files_to_android() missing 1 required positional argument: 'package_name'
```

### Reproduce steps

I successfully installed and configured the worddumb. but when I plug my android devices and click the word dumb button (kfx format files). the error says as follows

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/14c595ee13b0921de8f6ed48500ee6ae58b5e8c8 should fix this error. GitHub Actions is down again, you can install this zip file to test:

[worddumb-14c595ee13b0921de8f6ed48500ee6ae58b5e8c8.zip](https://github.com/xxyzz/WordDumb/files/9724150/worddumb-14c595ee13b0921de8f6ed48500ee6ae58b5e8c8.zip)

**Comment by monkeychenh** [comment]
thanks. I tried your zip file. the error is different now.
btw, are my android devices need to be rooted or not?

error is as follows.

calibre, version 6.6.1 (darwin, embedded-python: True)
adb failed: 

Traceback (most recent call last):
  File "calibre_plugins.worddumb.send_file", line 44, in send_files
    self.push_files_to_android(adb_path)
  File "calibre_plugins.worddumb.send_file", line 123, in push_files_to_android
    run_subprocess(
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/adb', 'push', PosixPath('/Volumes/CHWD750_2TB/Books/Calibre Library/Pablo Neruda/The Poetry of Pablo Neruda (9)/LanguageLayer.en.BBPQ4WYFMD.kll'), '/data/data/com.amazon.kindle/databases/WordWise.en.BBPQ4WYFMD.CR_8O1RWT521B70FBEZMMDXE3NEZZUC.db']' returned non-zero exit status 1.

**Comment by xxyzz** [comment]
Yes, move Word Wise file requires ROOT permission, X-Ray file doesn't.
