### ISSUE TITLE
not work on kindle paperwhite 11th

### ISSUE THREAD

**Issue by lele1122** [xxyzz/WordDumb#80]
### Describe the bug

It seems to not work on the latest kindle paperwhite 11th. I tried on my old kindle it works. Did I miss anything or it just does not support?

### System Information

N/A

### Error message

```text
N/A
```

### Reproduce steps

N/A

**Comment by xxyzz** [comment]
Could you fill out the reproduce steps and specify what function doesn't work?

If Word Wise doesn't display on your new device, it probably needs to connect to Wi-Fi and downloads the Word Wise database file.

**Comment by lele1122** [comment]
> Could you fill out the reproduce steps and specify what function doesn't work?
> 
> If Word Wise doesn't display on your new device, it probably needs to connect to Wi-Fi and downloads the Word Wise database file.

1. Put the file (EPUB) into calibre
2. convert books (to AZW3)
3. click "Create Word Wise". Then the book will show "On Device" with green check.
4. "Eject device" from calibre.

Open kindle, it showed "Downloading Word Wise...", but I waited for 1 hour still no progress.

I did not get that problem in my kindle paperwhite 6th (exactly the same steps, but it worked in it for the same book).

**Comment by lele1122** [comment]
Both kindles are registered to China Amazon. Does it impact?

**Comment by xxyzz** [comment]
Your older device already downloaded the Word Wise database file from Amazon previously. My guess is GFW is messing with you.

**Comment by lele1122** [comment]
I am not based in China but may related to the server in China. I just downloaded another book from China amazon store and it also got same "Downloading Word Wise...". I restarted the kindle but still the same.

 Do you know if I can copy that database from old one to the new one? What's the file name?
