### ISSUE TITLE
Covers won't show after using WordDumb

### ISSUE THREAD

**Issue by amerikaneca2** [xxyzz/WordDumb#82]
### Describe the bug

Hello,

so when I first transfer a book to my Kindle the cover is visible, but after I use the plugin the cover is no longer visible. Any help with that? 

Thanks.

### System Information

OS: Windows 10
calibre version: 6.7.1
Python version: 3.11
Plugin version: 3.25.0

### Error message

```text
none
```

### Reproduce steps

none

**Comment by xxyzz** [comment]
Kindle removes the cover if Wi-Fi is connected. Reconnect your Kindle to calibre and calibre will restore the cover for you.

Please read calibre FAQ: https://manual.calibre-ebook.com/faq.html#covers-for-books-i-send-to-my-e-ink-kindle-show-up-momentarily-and-then-are-replaced-by-a-generic-cover

**Comment by amerikaneca2** [comment]
I'm aware of this, that was happening while my wifi was turned off.  I'm constantly on airplane mode.

**Comment by amerikaneca2** [comment]
So I found out what the issue was.

I was first transferring the book to my kindle from calibre and then for whatever reason I disconnected from calibre, re connected and THEN applied the plugin.  (was still trying to figure out how it works lol) 

Obviously the right way to do it is to 
- transfer book to kindle
- after its transfered ----> apply WordDumb while stile being connected to Calibre.

Now I have my covers. X Ray is working as well!

Thank you xxyz.

**Comment by xxyzz** [comment]
If you send a book without a valid ASIN metadata to Kindle first then use WordDumb, WordDumb will set a random ASIN to the book and the cover thumbnail filename on Kindle will not match the new ASIN.

The right way is to let the plugin send the book to your Kindle: connect Kindle to calibre then click the plugin menu or icon.

**Comment by xxyzz** [comment]
Commit https://github.com/xxyzz/WordDumb/commit/a01c2e3478c8dcaae1112f26260da34a3e8d8023 re-uploads book cover to Kindle if ASIN is changed.

**Comment by amerikaneca2** [comment]
> Commit [a01c2e3](https://github.com/xxyzz/WordDumb/commit/a01c2e3478c8dcaae1112f26260da34a3e8d8023) re-uploads book cover to Kindle if ASIN is changed.

Sorry I'm a newbie, how do I do this exactly?

**Comment by xxyzz** [comment]
You can download and install the zip file(in the Artifacts section) with that change from here: https://github.com/xxyzz/WordDumb/actions/runs/3358001718

But you don't need to do this, the book cover won't disappear if you let the plugin to send that book.

**Comment by amerikaneca2** [comment]
YES, letting the plugin send the book worked.
I was first sending the book from Calibre and then applying WordDumb.

Thanks for your support!
