### ISSUE TITLE
Error for X-ray

### ISSUE THREAD

**Issue by joyq28** [xxyzz/WordDumb#84]
calibre, version 6.8.0 (win32, embedded-python: True)
Tonnerre de Brest!: 发生了一个错误，请复制错误信息并到 GitHub 提交错误报告。

Starting job: 正在为《The Valley of Fear》生成生词提示和X-Ray 
Job: "正在为《The Valley of Fear》生成生词提示和X-Ray" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 105, in do_job
  File "calibre_plugins.worddumb.deps", line 34, in install_deps
  File "calibre_plugins.worddumb.deps", line 68, in install_x_ray_deps
  File "calibre_plugins.worddumb.deps", line 108, in pip_install_pkgs
  File "calibre_plugins.worddumb.deps", line 103, in pip_install
  File "calibre_plugins.worddumb.utils", line 42, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', 'install', '-U', '-t', WindowsPath('C:/Users/joyq2/AppData/Roaming/calibre/plugins/worddumb-libs-py3.10'), '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--no-user', '--python-version', '3.10', 'numpy==1.23.1']' returned non-zero exit status 1.
 
Called with args: ((27, 'MOBI', 'D:\\图书\\Calibre书库\\Arthur Conan Doyle\\The Valley of Fear (27)\\The Valley of Fear - Arthur Conan Doyle.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x000002965A5DFD00>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x000002965A5DFF40>, 'abort': <threading.Event object at 0x000002965A5DF970>, 'log': <calibre.utils.logging.GUILog object at 0x000002965A5DFAF0>} 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/numpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/numpy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/numpy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/numpy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/numpy/
ERROR: Could not find a version that satisfies the requirement numpy==1.23.1 (from versions: none)
ERROR: No matching distribution found for numpy==1.23.1

**Comment by xxyzz** [comment]
Base on the numpy version, I guess you're using outdated plugin. Update to the latest version should fix this error.

**Comment by xxyzz** [comment]
v3.27.0 should fix this error, I'll close the issue.
