### ISSUE TITLE
Question: Use with kindle personal documents

### ISSUE THREAD

**Issue by raiden076** [xxyzz/WordDumb#85]
Hi, I usually send e books from calibre to kindle using email, and that way, it syncs on all of the devices,

Now, is there any way to use worddumb with ebooks(azw3) stored in a kindle, sent via email?

I know the x-rays and all won't sync up, but, only on one Kindle, is there any way to make it work?

**Comment by xxyzz** [comment]
Unfortunately, send to Kindle by Email doesn't support X-Ray and Word Wise files(https://www.amazon.com/gp/sendtokindle/email). And these two features don't support personal documents.
