### ISSUE TITLE
error on newest version

### ISSUE THREAD

**Issue by avijitb129** [xxyzz/WordDumb#88]
### Checkboxes

- [X] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

can't open worddumb preferences

### System Information

win10
calibre 6.9
python 3.10
worddumb 3.27

### Error message

```text
calibre, version 6.9.0
ERROR: Unhandled exception: <b>ValueError</b>:too many values to unpack (expected 2)

calibre 6.9  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && Package KFX (from KFX Input) (1, 50, 0) && APNX Generator (1, 1, 0) && Count Pages (1, 12, 0) && Extract ISBN (1, 6, 0) && Goodreads (1, 7, 1) && Goodreads Sync (1, 16, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && Quality Check (1, 13, 2) && WordDumb (3, 27, 0) && ePub Extended Metadata {Writer} (0, 8, 1) && ePub Extended Metadata {Reader} (0, 8, 1) && ePub Extended Metadata (0, 8, 1)
Traceback (most recent call last):
  File "calibre_plugins.worddumb.ui", line 73, in config
  File "calibre\customize\__init__.py", line 156, in do_user_config
  File "calibre_plugins.worddumb.__init__", line 23, in config_widget
  File "calibre_plugins.worddumb.config", line 130, in __init__
ValueError: too many values to unpack (expected 2)
```

### Reproduce steps

1. update calibre to 6.9
2. update worddumb to latest version and this error will show

**Comment by xxyzz** [comment]
Thanks for your report, https://github.com/xxyzz/WordDumb/commit/085890fd9e965b3a1293547087187f667553e527 fixes this error.

**Comment by xxyzz** [comment]
v3.27.1 includes the fix commit, please update your plugin in calibre.

**Comment by avijitb129** [comment]
Updated the plugin and the error didn't appear this time. Thanks

**Comment by avijitb129** [comment]
How do I a use fandom to create word wise? For example, I want to use https://gameofthrones.fandom.com .But I'm not exactly sure how to use this feature

**Comment by xxyzz** [comment]
Some Fandom sites have multiple languages, you could put https://gameofthrones.fandom.com/da in the Fandom URL input box to use the Danish wiki.
