### ISSUE TITLE
X-ray inaccuracies 

### ISSUE THREAD

**Issue by ali-oem** [xxyzz/WordDumb#9]
After using this module for months, i noticed that the X-ray generated for books contained a lot of inaccuracies : 
*Sometime a letter got an x-ray entry 
*Some word like 'chapter' also getting entries

I have also tried https://github.com/Ephemerality/xray-builder.gui , and it gave better X-ray files, would be great if you could give a look and maybe incorporate it inside Worddumb, Thanks !
![photo_2021-08-31_07-52-45](https://user-images.githubusercontent.com/71282548/131456323-75c2ec16-e1a0-4679-bd69-0b8b5df958ca.jpg)

**Comment by xxyzz** [comment]
You should use the bug report template. The latest version(3.11.2) shouldn't have the two issues you mentioned.

**Comment by xxyzz** [comment]
xray-builder.gui seems to get x-ray data from https://www.revensoftware.com/roentgen which is closed source.

**Comment by ali-oem** [comment]
> xray-builder.gui seems to get x-ray data from https://www.revensoftware.com/roentgen which is closed source.
> 
> Use 'md' or 'lg' spaCy model will improve x-ray quality.

Can you please refer to me what each spaCy model is or does?

**Comment by xxyzz** [comment]
The model file size and NER precision can be found at https://spacy.io/models/en
