### ISSUE TITLE
X-Ray option in kindle does not show the X-Ray view

### ISSUE THREAD

**Issue by yetanotherketan** [xxyzz/WordDumb#99]
### Checkboxes

- [X] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

Created a X-Ray for a book after adding manual entries for multiple items using Custom X-Ray option.
Observing that X-Ray view is not opening after taping on X-Ray submenu on my Kindle.
However when I select a particular name/place, I can see X-Ray popup with manually added information. Open X-Rya option in that pop up is also not working.

### System Information

OS: Windows 10
Calibre 6.11
Plugin 3.28.2

### Error message

```text
No error message shown by Kindle
```

### Reproduce steps

Create X-Ray for a book after adding manual entries for multiple items using Custom X-Ray option.

### Screenshots or videos

https://user-images.githubusercontent.com/123257664/213876366-19c23a17-17c9-4b3c-90e2-9937b2aef5b1.mp4
https://user-images.githubusercontent.com/123257664/213876370-21f9e49d-6d16-46f4-a40f-720550835bea.mp4

**Comment by xxyzz** [comment]
Have you tried restarting your Kindle? If that doesn't work please upload the generated X-Ray file, it's in the `.sdr` folder on Kindle and the filename is `XRAY.entities.ASIN.asc`.

**Comment by ketanarlulkar** [comment]
Just tried restarting Kindle and it did worked after that, thank you.
